def Fixed_Page():
    

    snooze(3)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fixed Pages"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed Pages_LCLabel").name, "Fixed Pages")
    
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
#     dragAndDrop(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 667, 93, ":Data & Analytics NYSE QA_FixedPagesViewerPane", 568, 145, DnD.DropNone)
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed Pages_LCLabel_3").name, "Fixed Pages")
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))

    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCTextField"), 139, 8, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "82760")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")

    snooze(8)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 223, 149, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCTextField"), 35, 6, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "5015")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(8)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Backspace>")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "7")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    test.passes("pass")
    snooze(8)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_SmallButton_3"))
    snooze(7)
    clickButton(waitForObject(":Data & Analytics NYSE QA_SmallButton_4"))
    test.passes("Pass")
    snooze(7)
    clickButton(waitForObject(":Data & Analytics NYSE QA_CommonButton"))
    test.passes("pass")
    snooze(5)
    clickButton(waitForObject(":Data & Analytics NYSE QA_SmallButton_5"))
    snooze(7)
    clickButton(waitForObject(":Data & Analytics NYSE QA_SmallButton_6"))
    test.passes("pass")
    snooze(7)

#     clickButton(waitForObject(":Data & Analytics NYSE QA.Show PDF_LCMultiButton"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Show PDF_LCMultiButton", "Save as PDF..."))
#     mouseClick(waitForObject(":Save.Save In:_JButton"), 8, 4, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Save.ComboBox.list_JList", "Desktop"), 56, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Save.File Name:_JTextField"), 31, 9, 0, Button.Button1)
#     type(waitForObject(":Save.File Name:_JTextField"), "fixedpages")
#     clickButton(waitForObject(":Save.Save_JButton"))
#     clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
#     clickButton(waitForObject(":Information.OK_FixedSizeButton"))

    snooze(5)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed Pages_LCLabel"), 13, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_8", "Watch List"))
    activateItem(waitForObjectItem(":Watch List_JMenu_6", "To the left"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel_4"), 0, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Watch List_LCLabel").name, "Watch List")
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_JPanel_16"), 511, 10, 0, Button.Button1)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed Pages_LCLabel"), 28, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel_5"), 1, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed Pages_LCLabel").name, "Fixed Pages")
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed Pages_LCLabel"), 22, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Titlebar description"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed Pages_LCLabel_2").text, "Fixed Pages")
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed Pages_LCLabel_2"), 9, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Customize Titlebar Description..."))
    type(waitForObject(":Titlebar Description Settings.Fixed Pages_LCTextArea"), "<Right>")
    type(waitForObject(":Titlebar Description Settings.Fixed Pages_LCTextArea"), "<Right>")
    type(waitForObject(":Titlebar Description Settings.Fixed Pages_LCTextArea"), "<Right>")
    type(waitForObject(":Titlebar Description Settings.Fixed Pages_LCTextArea"), "<Right>")
    type(waitForObject(":Titlebar Description Settings.Fixed Pages_LCTextArea"), "<Right>")
    type(waitForObject(":Titlebar Description Settings.Fixed Pages_LCTextArea"), "<Right>")
    type(waitForObject(":Titlebar Description Settings.Fixed Pages_LCTextArea"), " Test")
    mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 13, 9, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_5"))
    mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 12, 5, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.ColorPicker$ButtonsGrid_LCPanel"), 144, 38, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_6"))
    snooze(2)

    mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 9, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 93, 0, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "Palatino Linotype"), 67, 4, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 13, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "14"), 11, 14, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 7, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 4, 6, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel").text, "Fixed  TestPages")

    snooze(3)

    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 12, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Out"))
    test.compare(waitForObjectExists(":Fixed Pages.Fixed  TestPages_LCLabel").text, "Fixed  TestPages")
    mouseClick(waitForObject(":Fixed Pages.Fixed  TestPages_LCLabel"), 24, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Fixed Pages_TitlebarPanel", "Close"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 26, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Cut Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Empty Window_LCLabel"), 22, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Fixed Pages"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Fixed Pages_JMenu_2", "In this window"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel").text, "Fixed  TestPages")
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 17, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 18, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Fixed Pages"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Fixed Pages_JMenu_2", "To the left"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel").text, "Fixed  TestPages")
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 19, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window Image"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 26, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Fixed Pages"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Fixed Pages_JMenu_2", "To the left"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel").text, "Fixed  TestPages")
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 19, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Send Image by E-mail..."))
    test.passes("pass")
    snooze(1)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 14, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Take Custom Screenshot"))
    test.passes("pass")
    snooze(1)
    
    mouseDrag(waitForObject(":Data & Analytics NYSE QA.com.futuresource.livecharts.common.LCLabel_LCLabel"), 2, 0, 1332, 492, Modifier.None, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 13, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_3").text, "Text & Colors")
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed  TestPages_LCLabel"), 23, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Empty"))
    test.passes("pass")
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fixed Pages"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed Pages_LCLabel"), 14, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Close"))
    test.passes("pass")
    snooze(1)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fixed Pages"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed Pages_LCLabel"), 8, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Refresh"))
    test.passes("pass")
    
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Commodities"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Commodities.Commodity News"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Commodities.Commodity News.Technical Analysis: S&P 500 Nasdaq [80306]"), 178, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fixed Pages_LCLabel"), 11, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Refresh"))
    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCTextField"), 106, 10, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "81202")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.com.futuresource.livecharts.fixedpages.FixedPagesPad$FixedPagesPageComboBox_EditableComboBox"), 61, 1, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "83709")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(3)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Backspace>")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Backspace>")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "52")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(3)

    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCTextField"), 62, 10, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Backspace>")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "83067")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(3)
    


    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCTextField"), 88, 9, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Backspace>")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "80051")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(3)
    
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Backspace>")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "5")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")

    snooze(3)

    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 172, 81, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Back"))
    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 193, 109, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Forward"))
    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 231, 88, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Previous News"))
    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 194, 98, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Next News"))
    test.passes("pass")
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 182, 90, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Refresh"))
    test.passes("pass")
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 271, 147, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Search"))
    type(waitForObject(":Data & Analytics NYSE QA.Find:_LCTextField"), "<#20>")
    type(waitForObject(":Data & Analytics NYSE QA.Find:_LCTextField"), "EDT")
    clickButton(waitForObject(":Data & Analytics NYSE QA_SmallButton_7"))
    test.passes("pass")
    snooze(1)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 186, 85, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Hide Tree"))
    test.passes("pass")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 460, 96, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Show Tree"))
    test.passes("pass")
    snooze(2)
    


    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 231, 36, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Add to Favorites"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    setValue(waitForObject(":Data & Analytics NYSE QA_JScrollBar_2"), 0)
    test.compare(waitForObjectExists(":ICE Softs Closing Est. Vol [83752]_TreeItemProxy_2").text, "ICE Softs Closing Est. Vol [83752]")

    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 6, 39, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Dow Jones Energy"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Dow Jones Energy_JMenu", "Energy News Topics"))
    activateItem(waitForObjectItem(":Energy News Topics_JMenu", "Energy News Highlights [28036]"))
    test.passes("pass")
    snooze(5)

    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 10, 57, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Platts News"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Platts News_JMenu", "PBF Platts Biofuels News"))
    activateItem(waitForObjectItem(":PBF Platts Biofuels News_JMenu", "Deals"))
    activateItem(waitForObjectItem(":Deals_JMenu", "US Ethanol Deals [209]"))
    test.passes("pass")
    snooze(6)
    

    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 14, 31, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Save as PDF..."))
    mouseClick(waitForObject(":Save.Save In:_JButton"), 3, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Save.ComboBox.list_JList", "Desktop"), 60, 13, 0, Button.Button1)
    mouseClick(waitForObject(":Save.File Name:_JTextField"), 37, 13, 0, Button.Button1)
    type(waitForObject(":Save.File Name:_JTextField"), "fixedpages1")
    clickButton(waitForObject(":Save.Save_JButton"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    test.passes("pass")
    snooze(7)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 2, 36, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Send PDF by E-mail..."))
    test.passes("pass")
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 20, 56, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Print"))
    clickButton(waitForObject(":Print Fixed Pages.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    
    #mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 13, 43, 4, Button.Button3)
    #mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 541, 230, 0, Button.Button1)
    snooze(5)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 61, 124, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_9", "Save Fixed Pages Properties As Default"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 102, 87, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_3"), 24, 11, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "17"), 10, 19, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 86, 134, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_9", "Save Fixed Pages Properties As Default"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    test.passes("pass")
    snooze(1)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 45, 62, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_9", "Apply Default Properties to the Fixed Pages"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fixed Pages"))
    test.passes("pass")
    snooze(1)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 120, 127, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_9", "Apply Default Properties to all Fixed Pages Windows"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fixed Pages"))
    test.passes("pass")
    snooze(1)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 53, 101, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_9", "Remove Default Fixed Pages Properties"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fixed Pages"))
    test.passes("pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Favorites.ICE Softs Closing Est__ Vol [83752]"), 92, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 68, 100, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 105, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "Open Sans Semibold"), 44, 14, 0, Button.Button1)
    mouseClick(waitForObject(":Fixed Pages Display Properties_CommonButton"), 13, 5, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "14"), 18, 5, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton_5"))
    clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_5"))
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    test.passes("pass")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 231, 110, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton_6"))
    clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    test.passes("pass")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 103, 146, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 103, 8, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "Dialog"), 60, 13, 0, Button.Button1)
    mouseClick(waitForObject(":Fixed Pages Display Properties_CommonButton_2"), 3, 2, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "14"), 12, 4, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    test.passes("pass")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 136, 111, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    mouseClick(waitForObjectItem(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Fixed Pages Page  "), 52, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Fixed Pages Display Properties.Show Page in Separate Window_LCCheckBox"), 7, 9, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Energy"), 440, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.Reuse Page Window_LCCheckBox"), 12, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCPanel_LCPanel"), 12, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Fixed Pages Display Properties.Show Page in Separate Window_LCCheckBox"), 7, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Fixed Pages Display Properties.com.futuresource.livecharts.dialogs.DialogButtonPanel_DialogButtonPanel"), 384, 30, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Favorites.ICE Softs Closing Est__ Vol [83752]"), 103, 10, 0, Button.Button1)
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Energy"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Energy.Energy News Topics"))
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Energy.Energy News Topics.Energy News Highlights [28036]"), 47, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 140, 92, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.Show Page in Separate Window_LCCheckBox"), 14, 7, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Favorites.ICE Softs Closing Est__ Vol [83752]"), 63, 10, 0, Button.Button1)
    clickButton(waitForObject(":Fixed page.Close_JButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Energy.Energy News Topics"), 452, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "Display Properties..."))
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Energy.Energy News Topics.Energy News Highlights [28036]"), 59, 10, 0, Button.Button1)
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Favorites.ICE Softs Closing Est__ Vol [83752]"), 67, 10, 0, Button.Button1)
    snooze(3)
    clickButton(waitForObject(":Fixed page.Close_JButton"))

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Pages.Dow Jones Energy.Energy News Topics"), 459, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.Show Page in Separate Window_LCCheckBox"), 11, 9, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    test.passes("pass")
    snooze(3)

    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 68, 109, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.Use Printer Friendly Colors_LCCheckBox"), 5, 8, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA_FixedPagesViewerPane"), 113, 104, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_FixedPagesViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fixed Pages Display Properties.Use Printer Friendly Colors_LCCheckBox"), 3, 9, 0, Button.Button1)
    clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
    test.passes("pass")

    snooze(30)
#     clickButton(waitForObject(":Connect_JButton_4"))
#     activateItem(waitForObjectItem(":Connect_JButton_4", "Fixed Pages"))
#     waitFor("object.exists(':Fixed Pages.Fixed Pages_LCLabel')", 20000)
#     test.compare(findObject(":Fixed Pages.Fixed Pages_LCLabel").name, "Fixed Pages")
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy"))
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Energy News Topics"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Energy News Topics.Energy News Highlights [28036]"), 29, 9, 0, Button.Button1)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Market Talk"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Market Talk.DOE Oil Data: Gas, Distillate Stock Levels [81957]"), 43, 9, 0, Button.Button1)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Crude Oil Commentary"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Crude Oil Commentary.CFTC Commitments: Nymex crude oil Futures/Options - (Date) [88881]"), 70, 9, 0, Button.Button1)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.U__S__ Dept of Energy - Oil"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.U__S__ Dept of Energy - Oil.DOE Oil Data: Crude Production, Inputs, Utilization [8842]"), 60, 9, 0, Button.Button1)
#     setValue(waitForObject(":Fixed Pages_JScrollBar"), 413)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Natural Gas Commentary"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Natural Gas Commentary.Nymex Natural Gas Close [70551]"), 44, 9, 0, Button.Button1)
#     setValue(waitForObject(":Fixed Pages_JScrollBar"), 665)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Nymex"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Energy.Nymex.Nymex Harbor RBOB Gas Options Close [81935]"), 36, 9, 0, Button.Button1)
#     setValue(waitForObject(":Fixed Pages_JScrollBar"), 1295)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities"))
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities"))
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Commodity News"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Commodity News.USDA Sugarbeet Crop Progress [83679]"), 39, 9, 0, Button.Button1)
#     setValue(waitForObject(":Fixed Pages_JScrollBar"), 2015)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Softs"))
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Softs.Coffee"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Softs.Coffee.International Coffee Organization Prices [83692]"), 40, 9, 0, Button.Button1)
#     setValue(waitForObject(":Fixed Pages_JScrollBar"), 2861)
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Soy-Corn-Wheat-Rice"))
#     expand(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Soy-Corn-Wheat-Rice.Soybeans-Meal-Oil"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Soy-Corn-Wheat-Rice.Soybeans-Meal-Oil.USDA Loan Activity: Wheat, corn, soybeans, Cotton [82491]"), 31, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Fixed Pages_SmallButton"))
#     clickButton(waitForObject(":Fixed Pages_SmallButton_2"))
#     clickButton(waitForObject(":Fixed Pages_SmallButton_3"))
#     clickButton(waitForObject(":Fixed Pages_SmallButton_4"))
#     clickButton(waitForObject(":Fixed Pages_SmallButton_5"))
#     mouseClick(waitForObject(":Fixed Pages_JPanel"), 516, 15, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fixed Pages_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 66, 10, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "Open Sans Semibold"), 54, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties_CommonButton"), 6, 10, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "15"), 19, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 102, 6, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "DFKai-SB"), 75, 6, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties_CommonButton_2"), 13, 7, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fixed Pages Display Properties.ComboBox.list_JList", "15"), 10, 2, 0, Button.Button1)
#     clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton"))
#     clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton"))
#     clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton_2"))
#     clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Fixed Pages Display Properties. _FixedSizeButton_3"))
#     clickButton(waitForObject(":Fixed Pages Display Properties_FixedSizeButton_3"))
#     clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Fixed Pages_JPanel"), 493, 12, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fixed Pages_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObjectItem(":Fixed Pages Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Fixed Pages Page  "), 82, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Show Page in Separate Window_LCCheckBox"), 7, 1, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Use Printer Friendly Colors_LCCheckBox"), 5, 17, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Reuse Page Window_LCCheckBox"), 11, 14, 0, Button.Button1)
#     clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Fixed Pages_JPanel"), 455, 7, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fixed Pages_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Use Printer Friendly Colors_LCCheckBox"), 7, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Reuse Page Window_LCCheckBox"), 10, 8, 0, Button.Button1)
#     clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Fixed Pages_JPanel"), 455, 11, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fixed Pages_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Reuse Page Window_LCCheckBox"), 7, 4, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Use Printer Friendly Colors_LCCheckBox"), 11, 8, 0, Button.Button1)
#     clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Fixed Pages_JPanel"), 515, 7, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fixed Pages_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Fixed Pages Display Properties.Reuse Page Window_LCCheckBox"), 10, 7, 0, Button.Button1)
#     clickButton(waitForObject(":Fixed Pages Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Fixed Pages_FixedPagesTree", "All Pages.Dow Jones Commodities.Softs.Coffee.ICE Futures Markets Report [83742]"), 138, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Fixed page_HtmlViewerPane"), 298, 53, 0, Button.Button1)
#     clickButton(waitForObject(":Fixed page.Close_SmallButton"))
#     clickButton(waitForObject(":Fixed Pages_JButton"))

    
    
    Fundamentals()
