def Forex():
    
    
    snooze(3)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    snooze(1)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Forex"))
    snooze(1)
    clickButton(waitForObject(":Forex_JButton_2"))
    snooze(1)
    activateItem(waitForObjectItem(":Forex_JButton_2", "Attach"))

    snooze(3)     
    clickButton(waitForObject(":Data & Analytics NYSE QA_CommonButton_2"))
    clickButton(waitForObject(":Symbol Lookup.Search_FixedSizeButton"))
    snooze(2)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.dialogs.symbollookup.SymbolLookupDialog$SymbolsTable.USD A0-FX_TableItemProxy").text, "USD A0-FX")
    dragItemBy(waitForObject(":Symbol Lookup_LCTitlePane"), 62, 12, -461, -584, Modifier.None, Button.Button1)
    clickButton(waitForObject(":Symbol Lookup.OK_FixedSizeButton"))
    
    #Context menu options 
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 18, 8, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_6", "Forex"))
#     activateItem(waitForObjectItem(":Forex_JMenu", "To the left"))
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex_LCLabel").name, "Forex")
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#      
#  
#  
# #     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 19, 11, 4, Button.Button3)
# #     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
# #     mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel_7"), 8, 6, 4, Button.Button3)
# #     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
# #     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex_LCLabel").text, "Forex")
#  
#     snooze(3)
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 12, 13, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Titlebar description"))
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex_LCLabel_2").text, "Forex")
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel_2"), 9, 13, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Customize Titlebar Description..."))
#     mouseClick(waitForObject(":Titlebar Description Settings.Forex_LCTextArea"), 62, 11, 0, Button.Button1)
#     type(waitForObject(":Titlebar Description Settings.Forex_LCTextArea"), " test")
#     mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 6, 10, 0, Button.Button1)
#     clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
#     clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton"))
#     mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 8, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
#     clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_2"))
#     mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 6, 11, 0, Button.Button1)
#     mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 8, 13, 0, Button.Button1)
#     mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 9, 8, 0, Button.Button1)
#     clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex test_LCLabel").text, "Forex test")
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 15, 5, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Out"))
#     mouseClick(waitForObject(":Forex.Forex test_LCLabel"), 14, 1, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex_TitlebarPanel", "Attach"))
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex test_LCLabel").text, "Forex test")
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 539, 15, 0, Button.Button1)
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 17, 5, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 32, 15, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Forex"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Forex_JMenu", "To the left"))
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex test_LCLabel").text, "Forex test")
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 582, 19, 0, Button.Button1)
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 16, 8, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Cut Window"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Empty Window_LCLabel"), 26, 6, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Forex"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Forex_JMenu", "To the left"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 16, 17, 4, Button.Button3)
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex test_LCLabel").text, "Forex test")
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 496, 19, 0, Button.Button1)
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#      
#     clickButton(waitForObject(":Data & Analytics NYSE QA.Forex_MonsoonNewPadButton"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 11, 6, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window Image"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 19, 6, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Forex"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Forex_JMenu_2", "To the left"))
#     test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Forex test_LCLabel").text, "Forex test")
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex test_LCLabel"), 350, 6, 0, Button.Button1)
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Empty Window_LCLabel"), 27, 12, 4, Button.Button3)
#     clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 21, 10, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Send Image by E-mail..."))
#     test.passes("Pass")
#     snooze(2)
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 13, 7, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Take Custom Screenshot"))
#     mouseDrag(waitForObject(":Data & Analytics NYSE QA.com.futuresource.livecharts.common.LCLabel_LCLabel"), 8, 0, 1302, 512, Modifier.None, Button.Button1)
#     test.passes("Pass")
#     snooze(2)
#  
#     mouseClick(waitForObject(":Data & Analytics NYSE QA_JPanel_16"), 9, 1, 4, Button.Button3)
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 10, 14, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
#     test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_4").text, "Text & Colors")
#     clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
#  
#     snooze(3)
#      
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 7, 14, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Empty"))
#     test.passes("Pass")
#     snooze(2)
#      
#     clickButton(waitForObject(":Data & Analytics NYSE QA.Forex_MonsoonNewPadButton"))
#     mouseClick(waitForObject(":Data & Analytics NYSE QA.Forex_LCLabel"), 16, 14, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Close"))
#     test.passes("Pass")
#     snooze(2)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Forex_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 96, 67, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 96, 67, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "ib")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Backspace>")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "nr a0-fx")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 99, 58, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 99, 58, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "gbp a0-fx")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(3)

    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_MQMenuBar_2", "Tools"))
    activateItem(waitForObjectItem(":Tools_JMenu_3", "__Preferences..."))
    mouseClick(waitForObjectItem(":Preferences.com.futuresource.livecharts.common.LCCardList$1_LCList", "Appearance  "), 55, 12, 0, Button.Button1)
    mouseClick(waitForObject(":Preferences.Group available windows in context menu_LCCheckBox"), 20, 11, 0, Button.Button1)
    clickButton(waitForObject(":Preferences.Apply_FixedSizeButton"))
    clickButton(waitForObject(":Preferences.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 67, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_10", "Stock Options"))
    test.compare(waitForObjectExists(":Stock Options.Stock Options_LCLabel_2").text, "Stock Options")
    clickButton(waitForObject(":Stock Options_JButton"))
    snooze(3)

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 133, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_20", "Dow/S&P/NYSE"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 131, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_20", "Equities"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 134, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_20", "Futures"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 114, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_20", "Market Stats"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 110, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_20", "Mkt Overview"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 83, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Mobile Home Page (Phone Only)"))
    activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_13", "Stocks"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 91, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Mobile Home Page (Phone Only)"))
    activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_13", "Futures"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 84, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Mobile Home Page (Phone Only)"))
    activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_13", "US"))
    mouseClick(waitForObject(":Information.com.futuresource.livecharts.dialogs.DialogButtonPanel_DialogButtonPanel"), 189, 5, 0, Button.Button1)
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 98, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_15", "Mobile Home Page (Phone Only)"))
    activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_13", "Forex"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(3)

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 79, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_17", "Add Price Alert"))
    type(waitForObject(":Add Price Alert_LCTextField"), "1.5")
    mouseClick(waitForObject(":Add Price Alert.Link To:_LCCheckBox"), 10, 12, 0, Button.Button1)
    mouseClick(waitForObject(":Add Price Alert_LCTextArea"), 120, 36, 0, Button.Button1)
    type(waitForObject(":Add Price Alert_LCTextArea"), "test")
    clickButton(waitForObject(":Add Price Alert.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 74, 22, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_17", "Add News Alert"))
    mouseClick(waitForObject(":Add News Alert.Link To:_LCCheckBox"), 14, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Add News Alert_LCTextArea"), 38, 38, 0, Button.Button1)
    type(waitForObject(":Add News Alert_LCTextArea"), "test")
    clickButton(waitForObject(":Add News Alert.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 81, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_17", "Add Data Alert"))
    mouseClick(waitForObject(":Add Data Alert_LCTextArea"), 131, 39, 0, Button.Button1)
    type(waitForObject(":Add Data Alert_LCTextArea"), "test")
    mouseClick(waitForObject(":Add Data Alert.Email notify: _LCCheckBox"), 9, 7, 0, Button.Button1)
    clickButton(waitForObject(":Add Data Alert.Cancel_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 73, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_17", "Add News Alert_1"))
    mouseClick(waitForObject(":Add News Alert_LCTextArea_2"), 85, 37, 0, Button.Button1)
    type(waitForObject(":Add News Alert_LCTextArea_2"), "test")
    mouseClick(waitForObject(":Add News Alert.Email notify: _LCCheckBox"), 8, 11, 0, Button.Button1)
    clickButton(waitForObject(":Add News Alert.Cancel_FixedSizeButton_2"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 83, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_17", "__Alerts"))
    test.compare(waitForObjectExists(":Alerts.Alerts_LCLabel_3").name, "Alerts")
    clickButton(waitForObject(":Alerts_JButton"))
    snooze(3)
    



    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 94, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Notes"))
    mouseClick(waitForObject(":Note - US DOLLAR/BRITISH POUND_LCToggleButton"), 7, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Note - US DOLLAR/BRITISH POUND_LCToggleButton_2"), 9, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Note - US DOLLAR/BRITISH POUND_LCToggleButton_3"), 5, 12, 0, Button.Button1)
    clickButton(waitForObject(":Note - US DOLLAR/BRITISH POUND. _FixedSizeButton"))
    clickButton(waitForObject(":Note - US DOLLAR/BRITISH POUND_FixedSizeButton"))
    type(waitForObject(":Note - US DOLLAR/BRITISH POUND_JTextPane"), "test notes")
    clickButton(waitForObject(":Note - US DOLLAR/BRITISH POUND.OK_FixedSizeButton"))

    snooze(2)
    
#     mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 61, 20, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Trade"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade_JMenu_4", "Buy INR A0-FX"))
#     snooze(2)
#     test.compare(waitForObjectExists(":Order Ticket - New Order.Buy_TradeButton").actioncommand, "Buy")
#     clickButton(waitForObject(":Order Ticket - New Order.Cancel_FixedSizeButton"))
#     test.passes("Pass")
#     snooze(2)
#     
#     mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 92, 23, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Trade"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade_JMenu_4", "Sell INR A0-FX"))
#     snooze(2)
#     test.compare(waitForObjectExists(":Order Ticket - New Order.Sell_TradeButton").actioncommand, "Sell")
#     clickButton(waitForObject(":Order Ticket - New Order.Cancel_FixedSizeButton"))
#     test.passes("Pass")
#     snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 61, 26, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Trade Details"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade Details_JMenu_3", "Show Positions"))
    test.compare(waitForObjectExists(":Account Manager.Account Manager_LCLabel").name, "Account Manager")
    clickButton(waitForObject(":Account Manager_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 66, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Trade Details"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade Details_JMenu_3", "Show Orders"))
    test.compare(waitForObjectExists(":Account Manager.Account Manager_LCLabel").name, "Account Manager")
    clickButton(waitForObject(":Account Manager_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 100, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Trade Details"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade Details_JMenu_3", "Show Executions"))
    test.compare(waitForObjectExists(":Account Manager.Account Manager_LCLabel").name, "Account Manager")
    clickButton(waitForObject(":Account Manager_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 71, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add New Symbol"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCTextField"), 29, 5, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "USD a0-fx")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")

    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 66, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Delete"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Delete_JMenu_3", "Selected Symbol(s)"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 90, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Delete"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Delete_JMenu_3", "All Symbols"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 126, 59, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 126, 59, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "gbp a0-fx")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 93, 59, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 93, 59, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "inr a0-fx")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")

    snooze(2)
    


    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 54, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Edit_JMenu_3", "Edit Selected Symbol"))
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "usd a0-fx")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")

    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 68, 63, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Edit_JMenu", "Cut Selected Symbol(s)"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 68, 58, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Edit_JMenu", "Paste Symbols"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 57, 58, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Edit_JMenu", "Copy Selected Symbol(s)"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 60, 54, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Edit_JMenu", "Paste Symbols"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 28, 58, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Select All"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 88, 52, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Clear Selection"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 77, 67, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show New Cell"))    
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 74, 50, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show New Cell"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 47, 56, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Changed Indicator"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 74, 49, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Changed Indicator"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 60, 53, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Alert Indicator"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 86, 44, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Alert Indicator"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 83, 59, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Insert Symbols from file..."))
    mouseClick(waitForObject(":Open.Look In:_JComboBox"), 348, 8, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Open.ComboBox.list_JList", "Desktop"), 33, 9, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Open_JList", "forex symbols.txt"), 89, 9, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 46, 40, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Print"))
    clickButton(waitForObject(":Print Forex.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 48, 37, 4, Button.Button3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_JViewport_2"), 428, 204, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 69, 36, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties_CommonButton_2"), 11, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "16"), 14, 19, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 84, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_17", "Save Forex Properties As Default"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 79, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_17", "Apply Default Properties to the Forex"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA.Forex_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 92, 77, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Insert Symbols from file..."))
    setValue(waitForObject(":Open_JScrollBar"), 465)
    mouseClick(waitForObjectItem(":Open_JList", "forex symbols.txt"), 100, 5, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 85, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_17", "Apply Default Properties to all Forex Windows"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Forex_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 87, 72, 4, Button.Button3)
    activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Insert Symbols from file..."))
    setValue(waitForObject(":Open_JScrollBar"), 465)
    mouseClick(waitForObjectItem(":Open_JList", "forex symbols.txt"), 32, 14, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    clickButton(waitForObject(":Forex_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 81, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_17", "Remove Default Forex Properties"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))

    snooze(3)    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Forex_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 67, 61, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Insert Symbols from file..."))
    mouseClick(waitForObjectItem(":Open_JList", "forex symbols.txt"), 63, 4, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    test.passes("Pass")
    snooze(2)

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 87, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties_CommonButton"), 0, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "Palatino Linotype"), 31, 12, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 18, 10, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "14"), 14, 2, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Bold_LCCheckBox"), 16, 3, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Italic_LCCheckBox"), 4, 11, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_7"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 135, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 111, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_10"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_5"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_11"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 85, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_6"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_12"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_11"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_13"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_12"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_14"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_7"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_15"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 110, 24, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_13"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_12"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_14"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_11"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_15"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 103, 39, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Change Indicator  "), 59, 4, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Changed Indicator_LCCheckBox"), 6, 9, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 83, 41, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show Changed Indicator_LCCheckBox"), 9, 5, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 75, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_8"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_10"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_9"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_11"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 91, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Formatting  "), 68, 6, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Number of Cells per Row: _CommonButton"), 8, 3, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "3"), 24, 13, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 218, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show New Cell_LCCheckBox"), 9, 6, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 141, 46, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show New Cell_LCCheckBox"), 6, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.com.futuresource.livecharts.common.LCPanel_LCPanel"), 12, 73, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Alert Indicator_LCCheckBox"), 13, 11, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 164, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show Alert Indicator_LCCheckBox"), 14, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Flags_LCCheckBox"), 5, 7, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 155, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show Flags_LCCheckBox"), 11, 6, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Symbol as Description_LCCheckBox"), 8, 8, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 145, 27, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Gridlines  "), 34, 3, 0, Button.Button1)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 6)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 7)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 8)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 9)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 10)
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_10"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_15"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    snooze(30)
    
#     waitFor("object.exists(':Forex.Forex_LCLabel')", 20000)
#     test.compare(findObject(":Forex.Forex_LCLabel").text, "Forex")
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 118, 67, 0, Button.Button1)
#     doubleClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 118, 67, 0, Button.Button1)
#     type(waitForObject(":Forex_UppercaseTextField"), "inr a0-fx")
#     type(waitForObject(":Forex_UppercaseTextField"), "<Return>")
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 71, 40, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 72, 18, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add New Symbol"))
#     type(waitForObject(":Forex_UppercaseTextField"), "rsd a0-fx")
#     type(waitForObject(":Forex_UppercaseTextField"), "<Return>")
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 19, 69, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Delete"))
#     activateItem(waitForObjectItem(":Forex.Delete_JMenu", "Selected Symbol(s)"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 72, 48, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 72, 48, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show New Cell"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 87, 18, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Changed Indicator"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 71, 10, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Alert Indicator"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 62, 17, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show New Cell"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 82, 11, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Changed Indicator"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 83, 11, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Alert Indicator"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 85, 21, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
#     mouseClick(waitForObject(":Forex Display Properties_CommonButton"), 8, 6, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "Open Sans Extrabold"), 45, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties_CommonButton_2"), 6, 5, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "16"), 17, 8, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Bold_LCCheckBox"), 14, 8, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Italic_LCCheckBox"), 14, 6, 0, Button.Button1)
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton"))
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_2"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_3"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_4"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_5"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_3"))
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_6"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_4"))
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_7"))
#     mouseClick(waitForObject(":Forex Display Properties.com.futuresource.livecharts.common.ColorPicker$ButtonsGrid_LCPanel"), 97, 141, 0, Button.Button1)
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_5"))
#     clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 155, 23, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
#     mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Change Indicator  "), 80, 7, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show Changed Indicator_LCCheckBox"), 8, 6, 0, Button.Button1)
#     clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 132, 22, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
#     mouseClick(waitForObject(":Forex Display Properties.Show Changed Indicator_LCCheckBox"), 7, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_8"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_6"))
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_9"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_3"))
#     clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 109, 25, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
#     mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Formatting  "), 56, 4, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 33, 10, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "1"), 22, 15, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show Symbol as Description_LCCheckBox"), 15, 5, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show Flags_LCCheckBox"), 8, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show Alert Indicator_LCCheckBox"), 9, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show New Cell_LCCheckBox"), 11, 7, 0, Button.Button1)
#     clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 241, 23, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
#     mouseClick(waitForObject(":Forex Display Properties.Show Flags_LCCheckBox"), 11, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show Alert Indicator_LCCheckBox"), 11, 9, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show New Cell_LCCheckBox"), 9, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Show Symbol as Description_LCCheckBox"), 4, 8, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Number of Cells per Row: _CommonButton"), 0, 7, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Number of Cells per Row: _CommonButton"), 9, 11, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex Display Properties.Number of Cells per Row: _CommonButton"), 13, 5, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "6"), 12, 19, 0, Button.Button1)
#     clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 147, 20, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
#     mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Gridlines  "), 54, 7, 0, Button.Button1)
#     clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_10"))
#     clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_6"))
#     setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 4)
#     setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 3)
#     clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 168, 19, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
#     clickButton(waitForObject(":Forex Display Properties.Close_JButton"))
#     mouseClick(waitForObject(":Forex_JPanel"), 237, 1, 4, Button.Button3)
#     mouseClick(waitForObject(":Forex_JPanel"), 76, 11, 0, Button.Button1)
#     mouseClick(waitForObject(":Forex_JViewport"), 112, 177, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex_JViewport", "Add New Symbol"))
#     type(waitForObject(":Forex_UppercaseTextField"), "rsd a0-fx")
#     type(waitForObject(":Forex_UppercaseTextField"), "<Return>")
#     mouseClick(waitForObject(":Forex_JViewport"), 244, 209, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex_JViewport", "Select All"))
#     mouseClick(waitForObject(":Forex_JViewport"), 283, 200, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex_JViewport", "Delete"))
#     activateItem(waitForObjectItem(":Forex.Delete_JMenu", "All Symbols"))
#     mouseClick(waitForObject(":Question_LCTitlePane"), 40, 20, 0, Button.Button1)
#     clickButton(waitForObject(":Question.No_FixedSizeButton"))
#     snooze(5)
#     mouseClick(waitForObject(":Forex_JViewport"), 207, 180, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex_JViewport", "Edit"))
#     snooze(10)
#     activateItem(waitForObjectItem(":Forex.Edit_JMenu", "Paste Symbols"))
#     mouseClick(waitForObject(":Forex_JViewport"), 302, 179, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex_JViewport", "Insert Symbols from file..."))
#     clickButton(waitForObject(":Open.Cancel_JButton"))
#     mouseClick(waitForObject(":Forex_JViewport"), 187, 165, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Forex_JViewport", "Defaults"))
#     activateItem(waitForObjectItem(":Forex.Defaults_JMenu", "Save Forex Properties As Default"))
#     mouseClick(waitForObject(":Information_LCTitlePane"), 37, 14, 0, Button.Button1)
#     clickButton(waitForObject(":Information.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Forex_JViewport"), 486, 201, 0, Button.Button1)
#     clickButton(waitForObject(":Forex_SmallButton"))
#     clickButton(waitForObject(":Symbol Lookup.Search_FixedSizeButton"))
#     clickButton(waitForObject(":Symbol Lookup.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Forex_JPanel"), 482, 16, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Forex.com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/3"), 181, 23, 0, Button.Button1)
#     clickButton(waitForObject(":Forex_JButton"))
    



    
    Fixed_Page()
