def Fundamentals():
    
    
    snooze(3)
    clickButton(waitForObject(":Data & Analytics NYSE QA.Fundamentals_MonsoonNewPadButton"))
    clickButton(waitForObject(":Fundamentals_JButton_2"))
    snooze(2)
    activateItem(waitForObjectItem(":Fundamentals_JButton_2", "Attach"))

    snooze(3)
    
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "cl")
    snooze(2)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")

#     snooze(2)
#     
#     type(waitForObject(":Data & Analytics NYSE QA_LCTextField_13"), "cl")
#     type(waitForObject(":Data & Analytics NYSE QA_LCTextField_13"), "<Return>")
    snooze(3)

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Key Items"), 62, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Ratios"), 41, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Dividend History"), 72, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Earnings Events"), 72, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Bond Analytics"), 43, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Issue Details"), 51, 9, 0, Button.Button1)
    snooze(3)
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference"))
    snooze(3)
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates"))
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.All Estimates"), 21, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.Income Statement"), 44, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.Balance Sheet"), 69, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.Cash Flow"), 66, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.Per Share"), 64, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.Valuation"), 61, 9, 0, Button.Button1)
    snooze(3)
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates"))
    snooze(3)
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Financial Research"))
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Financial Research.Income Statement"), 64, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Financial Research.Balance Sheet"), 63, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Financial Research.Cash Flow"), 63, 9, 0, Button.Button1)
    snooze(3)
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Financial Research"))
    snooze(3)
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats"))
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.Futures"), 23, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.World Markets"), 60, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.North America"), 72, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.Latin America"), 72, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.Asia & Australia"), 65, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.Europe"), 47, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.Nordic"), 44, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats.Middle East"), 52, 9, 0, Button.Button1)
    snooze(3)
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Market Insight and Stats"))
    snooze(3)
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.US Funds"))
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.US Funds.US ETF Profile"), 70, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.US Funds.US Fund Profile"), 70, 9, 0, Button.Button1)
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.US Funds.US Fund Profile"), 70, 9, 4, Button.Button3)
    snooze(3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "Add to Favorites"))
    snooze(3)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Favorites.US Fund Profile"), 73, 9, 0, Button.Button1)
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 71, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Back"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 106, 22, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Forward"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 119, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Refresh"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 107, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Lock Page"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 89, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Hide Tree"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 309, 20, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Show Tree"))
    snooze(3)

    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.All Estimates"), 56, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "Add to Favorites"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.Income Statement"), 70, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "Add to Favorites"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Consensus Estimates.Balance Sheet"), 64, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "Add to Favorites"))
    snooze(2)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 138, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Favorites"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Favorites_JMenu_2", "All Estimates"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 205, 26, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Favorites"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Favorites_JMenu_2", "Income Statement"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 208, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Favorites"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Favorites_JMenu_2", "Balance Sheet"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 161, 27, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Favorites"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Favorites_JMenu_2", "US Fund Profile"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 131, 22, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Corporate Reference"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Corporate Reference_JMenu", "Company Profile"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 162, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Corporate Reference"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Corporate Reference_JMenu", "Key Items"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 157, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Corporate Reference"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Corporate Reference_JMenu", "Ratios"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 120, 41, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Corporate Reference"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Corporate Reference_JMenu", "Dividend History"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 268, 22, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Corporate Reference"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Corporate Reference_JMenu", "Earnings Events"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 284, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Corporate Reference"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Corporate Reference_JMenu", "Bond Analytics"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 200, 36, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Corporate Reference"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Corporate Reference_JMenu", "Issue Details"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 148, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Consensus Estimates"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Consensus Estimates_JMenu", "All Estimates"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 147, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Consensus Estimates"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Consensus Estimates_JMenu", "Income Statement"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 179, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Consensus Estimates"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Consensus Estimates_JMenu", "Balance Sheet"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 107, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Consensus Estimates"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Consensus Estimates_JMenu", "Cash Flow"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 95, 17, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Consensus Estimates"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Consensus Estimates_JMenu", "Per Share"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 99, 27, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Consensus Estimates"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Consensus Estimates_JMenu", "Valuation"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 108, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Financial Research"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Financial Research_JMenu", "Income Statement"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 72, 44, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Financial Research"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Financial Research_JMenu", "Balance Sheet"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 49, 38, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Financial Research"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Financial Research_JMenu", "Cash Flow"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 51, 42, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "Futures"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 109, 51, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "World Markets"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 125, 30, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "North America"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 122, 34, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "Latin America"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 135, 49, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "Asia & Australia"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 125, 47, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "Europe"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 101, 24, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "Nordic"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 157, 33, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Market Insight and Stats"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Market Insight and Stats_JMenu", "Middle East"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 172, 16, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "US Funds"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.US Funds_JMenu", "US ETF Profile"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 99, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "US Funds"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.US Funds_JMenu", "US Fund Profile"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 75, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Save as PDF..."))
    clickButton(waitForObject(":Save.Cancel_JButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 105, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Print"))
    clickButton(waitForObject(":Print Fundamentals.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 82, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fundamentals Display Properties_CommonButton_5"), 1, 8, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "16"), 15, 10, 0, Button.Button1)
    clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 106, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_13", "Save Fundamentals Properties As Default"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    snooze(2)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 132, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_13", "Apply Default Properties to the Fundamentals"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    snooze(2)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fundamentals"))
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "cl")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 75, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_13", "Apply Default Properties to all Fundamentals Windows"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 114, 11, 4, Button.Button3)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    snooze(2)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fundamentals"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 48, 34, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_13", "Remove Default Fundamentals Properties"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    snooze(2)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Fundamentals"))
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "cl")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Earnings Events"), 81, 9, 0, Button.Button1)
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_ResearchViewerPane"), 278, 17, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_ResearchViewerPane", "Display Properties..."))
    mouseClick(waitForObject(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_3"), 74, 11, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "Open Sans Extrabold"), 67, 6, 0, Button.Button1)
    mouseClick(waitForObject(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_4"), 24, 4, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "15"), 14, 1, 0, Button.Button1)
    clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Fundamentals Display Properties_CommonButton_3"))
    clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_7"))
    clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", "All Research.Corporate Reference.Issue Details"), 90, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fundamentals_LCLabel"), 43, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fundamentals_LCLabel"), 27, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    mouseClick(waitForObject(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_5"), 80, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "Plantagenet Cherokee"), 47, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 19, 3, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "15"), 3, 7, 0, Button.Button1)
    clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_5"))
    clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_10"))
    clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_6"))
    clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fundamentals_LCLabel"), 14, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    mouseClick(waitForObjectItem(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Fundamentals Page  "), 68, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 323, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "Open in Chart"), 68, 7, 0, Button.Button1)
    clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fundamentals_LCLabel"), 48, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    mouseClick(waitForObject(":Fundamentals Display Properties.Use Printer Friendly Colors_LCCheckBox"), 6, 7, 0, Button.Button1)
    clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Fundamentals_LCLabel"), 35, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    mouseClick(waitForObject(":Fundamentals Display Properties.Use Printer Friendly Colors_LCCheckBox"), 8, 11, 0, Button.Button1)
    snooze(2)
    mouseClick(waitForObject(":Fundamentals Display Properties.Continuous Printfolio Printing_LCCheckBox"), 6, 8, 0, Button.Button1)
    clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCTextField"), 61, 8, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField"), "ibm")
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA_LCAppendedButton_7"))
    snooze(3)
    #clickButton(waitForObject(":Data & Analytics NYSE QA_LCAppendedButton_2"))


    clickButton(waitForObject(":Data & Analytics NYSE QA_CommonButton"))
    snooze(3)
    clickButton(waitForObject(":Data & Analytics NYSE QA_SmallButton_5"))
    snooze(3)
    clickButton(waitForObject(":Data & Analytics NYSE QA_SmallButton_6"))
    snooze(3)
    clickButton(waitForObject(":Data & Analytics NYSE QA_LCAppendedButton_8"))
    snooze(3)
    clickButton(waitForObject(":Symbol Lookup.Search_FixedSizeButton"))
    snooze(3)
    clickButton(waitForObject(":Symbol Lookup.OK_FixedSizeButton"))

    snooze(40)
#     clickButton(waitForObject(":Connect_JButton_4"))
#     activateItem(waitForObjectItem(":Connect_JButton_4", "Fundamentals"))
#     dragItemBy(waitForObject(":Fundamentals_JPanel"), 413, 3, -146, 8, Modifier.None, Button.Button1)
#     waitFor("object.exists(':Fundamentals.Fundamentals_LCLabel')", 20000)
#     test.compare(findObject(":Fundamentals.Fundamentals_LCLabel").name, "Fundamentals")
#     mouseClick(waitForObject(":Fundamentals_LCTextField"), 63, 12, 0, Button.Button1)
#     type(waitForObject(":Fundamentals_LCTextField"), "cl")
#     type(waitForObject(":Fundamentals_LCTextField_3"), "<Return>")
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Corporate Reference.Key Items"), 48, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Corporate Reference.Ratios"), 47, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Corporate Reference.Ownership Summary"), 37, 9, 0, Button.Button1)
#     expand(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Consensus Estimates"))
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Consensus Estimates.Income Statement"), 62, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Consensus Estimates.Balance Sheet"), 51, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Consensus Estimates.All Estimates"), 50, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Consensus Estimates.Cash Flow"), 46, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Consensus Estimates.Per Share"), 47, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Consensus Estimates.Valuation"), 47, 9, 0, Button.Button1)
#     expand(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Financial Research"))
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Financial Research.Income Statement"), 18, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Financial Research.Balance Sheet"), 71, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Financial Research.Cash Flow"), 67, 9, 0, Button.Button1)
#     expand(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats"))
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.Futures"), 29, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.World Markets"), 38, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.North America"), 38, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.Latin America"), 45, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.Asia & Australia"), 49, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.Europe"), 43, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.Nordic"), 43, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.Middle East"), 44, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.Market Insight and Stats.Stock Splits"), 46, 9, 0, Button.Button1)
#     expand(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.US Funds"))
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.US Funds.US ETF Profile"), 30, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals_ResearchTree", "All Research.US Funds.US Fund Profile"), 52, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Fundamentals_LCAppendedButton"))
#     clickButton(waitForObject(":Fundamentals_LCAppendedButton_2"))
#     clickButton(waitForObject(":Symbol Lookup.Search_FixedSizeButton"))
#     clickButton(waitForObject(":Symbol Lookup.OK_FixedSizeButton"))
#     clickButton(waitForObject(":Fundamentals_SmallButton"))
#     clickButton(waitForObject(":Fundamentals_SmallButton_2"))
#     clickButton(waitForObject(":Fundamentals_SmallButton_3"))
#     mouseClick(waitForObject(":Fundamentals_JPanel_2"), 446, 8, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Fundamentals Display Properties_CommonButton"), 1, 8, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "Open Sans Semibold"), 83, 9, 0, Button.Button1)
#     mouseClick(waitForObject(":Fundamentals Display Properties_CommonButton_2"), 5, 10, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "15"), 15, 11, 0, Button.Button1)
#     clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton"))
#     clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton"))
#     clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_2"))
#     clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_3"))
#     clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_3"))
#     clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_4"))
#     clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_4"))
#     mouseClick(waitForObject(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 75, 11, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "PMingLiU"), 61, 2, 0, Button.Button1)
#     mouseClick(waitForObject(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 23, 14, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Fundamentals Display Properties.ComboBox.list_JList", "15"), 14, 12, 0, Button.Button1)
#     clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_5"))
#     clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_5"))
#     clickButton(waitForObject(":Fundamentals Display Properties. _FixedSizeButton_6"))
#     clickButton(waitForObject(":Fundamentals Display Properties_FixedSizeButton_6"))
#     clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Fundamentals_JPanel_2"), 433, 11, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObjectItem(":Fundamentals Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Fundamentals Page  "), 116, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Fundamentals Display Properties.Continuous Printfolio Printing_LCCheckBox"), 19, 6, 0, Button.Button1)
#     mouseClick(waitForObject(":Fundamentals Display Properties.Use Printer Friendly Colors_LCCheckBox"), 18, 13, 0, Button.Button1)
#     clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Fundamentals_JPanel_2"), 408, 11, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Fundamentals Display Properties.Use Printer Friendly Colors_LCCheckBox"), 14, 13, 0, Button.Button1)
#     mouseClick(waitForObject(":Fundamentals Display Properties.Continuous Printfolio Printing_LCCheckBox"), 15, 12, 0, Button.Button1)
#     clickButton(waitForObject(":Fundamentals Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Fundamentals_JPanel"), 630, 21, 4, Button.Button3)
#     mouseClick(waitForObject(":Fundamentals_LCPopupMenu"), 0, 6, 4, Button.Button3)
#     mouseClick(waitForObject(":Fundamentals_JPanel_2"), 483, 10, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_TitlebarPanel", "Refresh"))
#     mouseClick(waitForObject(":Fundamentals_JPanel_2"), 427, 7, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_TitlebarPanel", "Refresh"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 330, 45, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Lock Page"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 230, 22, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Hide Tree"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 322, 26, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Add to Favorites"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 311, 100, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Corporate Reference"))
#     activateItem(waitForObjectItem(":Fundamentals.Corporate Reference_JMenu", "Company Profile"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 267, 149, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Consensus Estimates"))
#     activateItem(waitForObjectItem(":Fundamentals.Consensus Estimates_JMenu", "Balance Sheet"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 408, 55, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Consensus Estimates"))
#     activateItem(waitForObjectItem(":Fundamentals.Consensus Estimates_JMenu", "Valuation"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 433, 79, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Market Insight and Stats"))
#     activateItem(waitForObjectItem(":Fundamentals.Market Insight and Stats_JMenu", "Europe"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 413, 18, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "US Funds"))
#     activateItem(waitForObjectItem(":Fundamentals.US Funds_JMenu", "US ETF Profile"))
#     mouseClick(waitForObject(":Fundamentals_ResearchViewerPane"), 378, 25, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Fundamentals_ResearchViewerPane", "Defaults"))
#     activateItem(waitForObjectItem(":Fundamentals.Defaults_JMenu", "Save Fundamentals Properties As Default"))
#     mouseClick(waitForObject(":Information_LCTitlePane"), 54, 14, 0, Button.Button1)
#     clickButton(waitForObject(":Information.OK_FixedSizeButton"))
#     clickButton(waitForObject(":Fundamentals. US ETF Profile_ResearchTreeButton"))
#     mouseClick(waitForObjectItem(":Fundamentals_LCTree", "All Research.Consensus Estimates.Per Share"), 47, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Fundamentals_JButton"))


