def Grid():
    

    snooze(3)
    clickButton(waitForObject(":Data & Analytics NYSE QA.Grid_MonsoonNewPadButton"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 39, 6, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 39, 6, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "=aapl+ibm")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "<Return>")
    snooze(2)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCToggleButton_4"), 11, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCToggleButton_5"), 7, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCToggleButton_6"), 10, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_CommonButton_2"), 13, 10, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.ComboBox.list_JList", "15"), 12, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCToggleButton_7"), 9, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCToggleButton_8"), 5, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_LCToggleButton_9"), 7, 11, 0, Button.Button1)
    clickButton(waitForObject(":Data & Analytics NYSE QA. _FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA. _FixedSizeButton_2"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_FixedSizeButton_2"))
    snooze(2)
    test.passes("Pass")
    clickButton(waitForObject(":Data & Analytics NYSE QA. _LCDropDownButton"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA. _LCDropDownButton", "No Border"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA. _LCDropDownButton"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA. _LCDropDownButton", "Outside Borders"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA. _LCDropDownButton"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA. _LCDropDownButton", "Top Border"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA. _LCDropDownButton"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA. _LCDropDownButton", "Left Border"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA. _LCDropDownButton"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA. _LCDropDownButton", "Bottom Border"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA. _LCDropDownButton"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA. _LCDropDownButton", "Right Border"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA. _FixedSizeButton_3"))
    snooze(2)
    test.passes("Pass")
    clickButton(waitForObject(":Data & Analytics NYSE QA_FixedSizeButton_3"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 54, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Insert"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Insert_JMenu_2", "Insert Row"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 53, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Insert"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Insert_JMenu_2", "Insert Column"))
    snooze(2)
    test.passes("Pass")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 18, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Delete"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Delete_JMenu_2", "Delete Row"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 20, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Delete"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Delete_JMenu_2", "Delete Column"))
    snooze(2)
    test.passes("Pass")

#     mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 50, 9, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Merge Cells"))
#     snooze(1)
#     mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 60, 7, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Split Cells"))
#     snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 24, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Merge Cells"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 50, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Color"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Color_JMenu", "Default Text Color"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 51, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Color"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Color_JMenu", "Default Background"))
    snooze(2)
    test.passes("Pass")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 36, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "No Border"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 41, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "Outside Borders"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 33, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "All Borders"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 41, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "Top Border"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 55, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "Left Border"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 51, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "Left Border"))
    snooze(2)
    test.passes("Pass")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 66, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "Left Border"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 55, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "Bottom Border"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 41, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Borders"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Borders_JMenu", "Right Border"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 55, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Horizontal Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Horizontal Alignment_JMenu", "Align Left"))
    snooze(2)
    test.passes("Pass")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 53, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Horizontal Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Horizontal Alignment_JMenu", "Align Center"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 51, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Horizontal Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Horizontal Alignment_JMenu", "Align Right"))
    snooze(1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 44, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Horizontal Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Horizontal Alignment_JMenu", "Default"))
    snooze(2)
    test.passes("Pass")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 55, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Vertical Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Vertical Alignment_JMenu", "Align Top"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 41, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Vertical Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Vertical Alignment_JMenu", "Align Middle"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 23, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Vertical Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Vertical Alignment_JMenu_2", "Align Bottom"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 29, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Vertical Alignment"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Vertical Alignment_JMenu_2", "Default"))
    snooze(2)
    test.passes("Pass")

    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 16, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    snooze(1)
    mouseClick(waitForObject(":Grid Display Properties_LCTitlePane"), 66, 14, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties_CommonButton"), 6, 1, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Grid Display Properties.ComboBox.list_JList", "PMingLiU"), 73, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties_CommonButton_2"), 5, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Grid Display Properties.ComboBox.list_JList", "14"), 13, 16, 0, Button.Button1)
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton"))
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton_2"))
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton_3"))
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton_5"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton_5"))
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton_6"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Grid Display Properties.OK_FixedSizeButton"))
    snooze(2)
    test.passes("Pass")


    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 8, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    snooze(1)
    mouseClick(waitForObjectItem(":Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Table  "), 45, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Table Headers_LCCheckBox"), 13, 12, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Gridlines_LCCheckBox"), 14, 12, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Scrollbars_LCCheckBox"), 13, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Tooltips_LCCheckBox"), 7, 10, 0, Button.Button1)
    clickButton(waitForObject(":Grid Display Properties.OK_FixedSizeButton"))
    snooze(2)
    test.passes("Pass")
    


    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 22, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))

    snooze(3)
    mouseClick(waitForObject(":Grid Display Properties_LCTitlePane"), 73, 14, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Locked table  "), 58, 4, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Enable selection_LCCheckBox"), 16, 9, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Table  "), 50, 1, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Table Headers_LCCheckBox"), 25, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.com.futuresource.livecharts.common.LCPanel_LCPanel"), 17, 52, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Gridlines_LCCheckBox"), 15, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Scrollbars_LCCheckBox"), 9, 3, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Show Tooltips_LCCheckBox"), 10, 7, 0, Button.Button1)
    clickButton(waitForObject(":Grid Display Properties.OK_FixedSizeButton"))
    snooze(2)
    test.passes("Pass")
    


    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 18, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))

    snooze(3)
    mouseClick(waitForObjectItem(":Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Formatting  "), 72, 3, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties.Use Conditional Formatting_LCCheckBox"), 11, 5, 0, Button.Button1)
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton_7"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton_7"))
    clickButton(waitForObject(":Grid Display Properties. _FixedSizeButton_8"))
    clickButton(waitForObject(":Grid Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Grid Display Properties.OK_FixedSizeButton"))


    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 48, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Text & Colors  "), 52, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Grid Display Properties_CommonButton_2"), 4, 5, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Grid Display Properties.ComboBox.list_JList", "17"), 18, 18, 0, Button.Button1)
    clickButton(waitForObject(":Grid Display Properties.OK_FixedSizeButton"))
    snooze(2)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 40, 17, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_12", "Save Grid Properties As Default"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 14, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_12", "Apply Default Properties to the Grid"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Grid_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 35, 8, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 35, 8, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "=aapl+ibm")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "<Return>")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 42, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_12", "Apply Default Properties to all Grid Windows"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Grid_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 42, 11, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 42, 11, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "=aapl+ibm")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "<Return>")
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 42, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_12", "Remove Default Grid Properties"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Grid_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 45, 10, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.worksheet.WTable_WTable", "0/0"), 45, 10, 0, Button.Button1)
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "=aapl+ibm")
    type(waitForObject(":Data & Analytics NYSE QA_LCTextField_37"), "<Return>")

    snooze(3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 10, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Watch List"))
    activateItem(waitForObjectItem(":Watch List_JMenu_8", "To the right"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA_PadTitlebarLeftPanel"), 17, 16, 4, Button.Button3)
    mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel_4"), 29, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel_3", "Show Window Title"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Watch List_LCLabel").name, "Watch List")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))

      
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 16, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Quotes Grid"))
    activateItem(waitForObjectItem(":Quotes Grid_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Quotes Grid_LCLabel").name, "Quotes Grid")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 9, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Chart"))
    activateItem(waitForObjectItem(":Chart_JMenu_18", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Chart_LCLabel").name, "Chart")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 12, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Stock Options"))
    activateItem(waitForObjectItem(":Stock Options_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Stock Options_LCLabel").text, "Stock Options")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 21, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "News"))
    activateItem(waitForObjectItem(":News_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.News_LCLabel").name, "News")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 17, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Hot Lists"))
    activateItem(waitForObjectItem(":Hot Lists_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Hot Lists_LCLabel").name, "Hot Lists")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 13, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Detailed Quotes"))
    activateItem(waitForObjectItem(":Detailed Quotes_JMenu_5", "To the right"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel"), 3, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel_3", "Show Window Title"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Detailed Quotes_LCLabel").name, "Detailed Quotes")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 14, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Alerts"))
    activateItem(waitForObjectItem(":Alerts_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Alerts_LCLabel_2").text, "Alerts")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 16, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Time & Sales"))
    activateItem(waitForObjectItem(":Time & Sales_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Time & Sales_LCLabel").text, "Time & Sales")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 14, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Market Depth"))
    activateItem(waitForObjectItem(":Market Depth_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Market Depth_LCLabel").name, "Market Depth")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 15, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Net House"))
    activateItem(waitForObjectItem(":Net House_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Net House_LCLabel").name, "Net House")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 7, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Web Feeds"))
    activateItem(waitForObjectItem(":Web Feeds_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Web Feeds_LCLabel").text, "Web Feeds")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 20, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Weather"))
    activateItem(waitForObjectItem(":Weather_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Weather_LCLabel").name, "Weather")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 8, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Fundamentals"))
    activateItem(waitForObjectItem(":Fundamentals_JMenu_7", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Fundamentals_LCLabel").name, "Fundamentals")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 13, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Research Center"))
    activateItem(waitForObjectItem(":Research Center_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Research Center_LCLabel").text, "Research Center")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 6, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Browser"))
    activateItem(waitForObjectItem(":Browser_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Browser_LCLabel").name, "Browser")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 12, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "ETFs & Funds"))
    activateItem(waitForObjectItem(":ETFs & Funds_JMenu_5", "US ETF Profile"))
    activateItem(waitForObjectItem(":US ETF Profile_JMenu_5", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.US ETF Profile_LCLabel").name, "US ETF Profile")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 14, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "ETFs & Funds"))
    activateItem(waitForObjectItem(":ETFs & Funds_JMenu_5", "CA ETF Profile"))
    activateItem(waitForObjectItem(":CA ETF Profile_JMenu_3", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 14, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "ETFs & Funds"))
    activateItem(waitForObjectItem(":ETFs & Funds_JMenu_5", "US Fund Profile"))
    activateItem(waitForObjectItem(":US Fund Profile_JMenu_5", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 17, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "ETFs & Funds"))
    activateItem(waitForObjectItem(":ETFs & Funds_JMenu_5", "Correlation Tracker"))
    activateItem(waitForObjectItem(":Correlation Tracker_JMenu_4", "To the top"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 18, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "ETFs & Funds"))
    activateItem(waitForObjectItem(":ETFs & Funds_JMenu_5", "ETF Liquidity Analyzer"))
    activateItem(waitForObjectItem(":ETF Liquidity Analyzer_JMenu_4", "To the left"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 18, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "ETFs & Funds"))
    activateItem(waitForObjectItem(":ETFs & Funds_JMenu_5", "ETF Performance Analyzer"))
    activateItem(waitForObjectItem(":ETF Performance Analyzer_JMenu_4", "To the bottom"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 15, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Market Rates"))
    activateItem(waitForObjectItem(":Market Rates_JMenu_4", "US Markets Rates"))
    activateItem(waitForObjectItem(":US Markets Rates_JMenu_4", "To the left"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 20, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Forex"))
    activateItem(waitForObjectItem(":Forex_JMenu_5", "In this window"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA.Grid_MonsoonNewPadButton"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 19, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Future Options"))
    activateItem(waitForObjectItem(":Future Options_JMenu_5", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 12, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Strip Calculator"))
    activateItem(waitForObjectItem(":Strip Calculator_JMenu_5", "To the bottom"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 15, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "Strip Calculator"))
    activateItem(waitForObjectItem(":Strip Calculator_JMenu_5", "To the bottom"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 10, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "S&P Research"))
    activateItem(waitForObjectItem(":S&P Research_JMenu_5", "To the top"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 15, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_10", "S&P Research Mutual Fund Quick View"))
    activateItem(waitForObjectItem(":S&P Research Mutual Fund Quick View_JMenu_4", "To the top"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 10, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel_8"), 9, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Grid_LCLabel").name, "Grid")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 17, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Titlebar description"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Grid_LCLabel_2").text, "Grid")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel_2"), 12, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Customize Titlebar Description..."))
    type(waitForObject(":Titlebar Description Settings.Grid_LCTextArea"), "Test ")
    mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 3, 7, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_7"))
    mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 6, 6, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_6"))
    setValue(waitForObject(":Titlebar Description Settings., Transparency: _LCSpinner"), 49)
    setValue(waitForObject(":Titlebar Description Settings., Transparency: _LCSpinner"), 48)
    mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 11, 4, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 93, 2, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "PMingLiU"), 87, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings_CommonButton_2"), 0, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "15"), 9, 2, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 9, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 7, 1, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 27, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Out"))
    test.compare(waitForObjectExists(":Grid.Test Grid_LCLabel").text, "Test Grid")
    snooze(2)
    mouseClick(waitForObject(":Grid.Test Grid_LCLabel"), 36, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Grid_TitlebarPanel", "Attach"))
    snooze(1)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(1)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 12, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Cut Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Empty Window_LCLabel"), 34, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Grid"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Grid_JMenu", "In this window"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Test Grid_LCLabel").text, "Test Grid")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 14, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 10, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Grid"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Grid_JMenu", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Test Grid_LCLabel_2").text, "Test Grid")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 28, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window Image"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 19, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Grid"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Grid_JMenu", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Test Grid_LCLabel_2").text, "Test Grid")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 10, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Send Image by E-mail..."))
    snooze(2)
    test.passes("Pass")
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 19, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Take Custom Screenshot"))
    snooze(2)
    test.passes("Pass")
    
    mouseDrag(waitForObject(":Data & Analytics NYSE QA.com.futuresource.livecharts.common.LCLabel_LCLabel"), 3, 4, 1335, 501, Modifier.None, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 10, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Print"))
    clickButton(waitForObject(":Print Grid.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    snooze(2)
    test.passes("Pass")
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 14, 17, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    clickButton(waitForObject(":Grid Display Properties.OK_FixedSizeButton"))
    snooze(2)
    test.passes("Pass")
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Grid_LCLabel"), 17, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Empty"))
    snooze(2)
    test.passes("Pass")
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Grid_MonsoonNewPadButton"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Grid_LCLabel"), 18, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Close"))
    snooze(2)
    test.passes("Pass")

    snooze(5)
    
    Weather()
