def Notes():

   
    snooze(3)

    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Notes"))
    snooze(2)
    clickButton(waitForObject(":Notes_JButton_2"))
    snooze(1)
    activateItem(waitForObjectItem(":Notes_JButton_2", "Attach"))
    snooze(3)     
    
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_6", "Attach"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel"), 31, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_18", "Watch List"))
    activateItem(waitForObjectItem(":Watch List_JMenu_14", "To the right"))
    snooze(3)
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Watch List_LCDropDownButton").actioncommand, "Watch List")
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel"), 21, 1, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_18", "Quotes Grid"))
    activateItem(waitForObjectItem(":Quotes Grid_JMenu_11", "To the right"))
    snooze(3)
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Quotes Grid_LCLabel").name, "Quotes Grid")
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel"), 31, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_18", "Chart"))
    activateItem(waitForObjectItem(":Chart_JMenu_27", "To the right"))
    snooze(3)
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Chart_LCLabel").name, "Chart")
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel"), 18, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_18", "Stock Options"))
    activateItem(waitForObjectItem(":Stock Options_JMenu_10", "To the right"))
    snooze(3)
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Stock Options_LCLabel").name, "Stock Options")
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(3)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel"), 11, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel_3"), 5, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Notes_LCLabel").text, "Notes")
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel"), 10, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Titlebar description"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Notes_LCLabel_2").text, "Notes")
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel_2"), 12, 11, 4, Button.Button3)
     
 
 
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel_2"), 32, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Customize Titlebar Description..."))
    type(waitForObject(":Titlebar Description Settings.Notes_LCTextArea"), "test ")
    mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 15, 8, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton"))
    mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 13, 11, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_6"))
    setValue(waitForObject(":Titlebar Description Settings., Transparency: _LCSpinner"), 49)
    setValue(waitForObject(":Titlebar Description Settings., Transparency: _LCSpinner"), 48)
    mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 14, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 73, 13, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "PMingLiU"), 74, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 16, 9, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "14"), 13, 12, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 7, 12, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 10, 6, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.test Notes_LCLabel").text, "test Notes")
 
    snooze(3)
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 7, 17, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Out"))
    test.compare(waitForObjectExists(":Notes.Test Notes_LCLabel").text, "Test Notes")
    mouseClick(waitForObject(":Notes.Test Notes_LCLabel"), 1272, 15, 0, Button.Button1)
    clickButton(waitForObject(":Notes_JButton"))
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 19, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Cut Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Empty Window_LCLabel"), 9, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Notes"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Notes_JMenu", "To the left"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Test Notes_LCLabel").text, "Test Notes")
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 22, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 12, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Notes"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Notes_JMenu", "To the left"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Test Notes_LCLabel").text, "Test Notes")
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 567, 17, 0, Button.Button1)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 12, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window Image"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 11, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Notes"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Notes_JMenu", "To the left"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Test Notes_LCLabel").text, "Test Notes")
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 587, 0, 0, Button.Button1)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 12, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Send Image by E-mail..."))
    test.passes("Pass")
 
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 12, 17, 4, Button.Button3)        
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Take Custom Screenshot"))
    test.passes("Pass")
    snooze(1)
     
    mouseDrag(waitForObject(":Data & Analytics NYSE QA.com.futuresource.livecharts.common.LCLabel_LCLabel"), 2, 0, 1341, 577, Modifier.None, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 14, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Print"))
    clickButton(waitForObject(":Print Notes.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    test.passes("Pass")
    snooze(1)
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 22, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_2").text, "Text & Colors")
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Test Notes_LCLabel"), 14, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Empty"))
    test.passes("Pass")
    snooze(1)
     
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton", "Notes"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Notes_LCLabel"), 8, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Close"))
    test.passes("Pass")
    snooze(1)
     
    mouseClick(waitForObject(":Data & Analytics NYSE QA_JComponent"), 76, 159, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA_JPanel_10"), 12, 8, 0, Button.Button1)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Notes"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Add_FixedSizeButton"))
    type(waitForObject(":Note - _LCTextField"), "<#20>")
    type(waitForObject(":Note - _LCTextField"), "IBM")
    mouseClick(waitForObjectItem(":Note - .ComboBox.list_JList", "IBM"), 45, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_LCToggleButton"), 12, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_LCToggleButton_2"), 14, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_LCToggleButton_3"), 7, 11, 0, Button.Button1)
    clickButton(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS. _FixedSizeButton"))
    clickButton(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_FixedSizeButton"))
    type(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_JTextPane"), "ibm notes")
    clickButton(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Add_FixedSizeButton"))
    snooze(1)
    type(waitForObject(":Note - _LCTextField"), "MSFT")
    snooze(2)
    mouseClick(waitForObjectItem(":Note - .ComboBox.list_JList", "MSFT"), 17, 14, 0, Button.Button1)
    mouseClick(waitForObject(":Note - MICROSOFT CORP_LCToggleButton"), 3, 14, 0, Button.Button1)
    mouseClick(waitForObject(":Note - MICROSOFT CORP_LCToggleButton_2"), 10, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Note - MICROSOFT CORP_LCToggleButton_3"), 12, 5, 0, Button.Button1)
    clickButton(waitForObject(":Note - MICROSOFT CORP. _FixedSizeButton"))
    clickButton(waitForObject(":Note - MICROSOFT CORP_FixedSizeButton"))
    type(waitForObject(":Note - MICROSOFT CORP_JTextPane"), "<#20>")
    type(waitForObject(":Note - MICROSOFT CORP_JTextPane"), "msft notes")
    clickButton(waitForObject(":Note - MICROSOFT CORP.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 19, 8, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "1/0"), 33, 5, 0, Button.Button1)
    clickButton(waitForObject(":Data & Analytics NYSE QA.Edit_FixedSizeButton"))
    type(waitForObject(":Note - MICROSOFT CORP_JTextPane"), " test")
    clickButton(waitForObject(":Note - MICROSOFT CORP.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Delete_FixedSizeButton"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Delete All_FixedSizeButton"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Import from CSV_FixedSizeButton"))
    mouseClick(waitForObject(":Open.Look In:_JButton"), 9, 0, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Open.ComboBox.list_JList", "Desktop"), 51, 14, 0, Button.Button1)
    setValue(waitForObject(":Open_JScrollBar"), 465)
    mouseClick(waitForObjectItem(":Open_JList", "symbolnotes.csv"), 69, 9, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Add_FixedSizeButton"))
    


    mouseClick(waitForObject(":Note - _LCTextField"), 54, 5, 0, Button.Button1)
    type(waitForObject(":Note - _LCTextField"), "<#20>")
    type(waitForObject(":Note - _LCTextField"), "ORCL")
    mouseClick(waitForObjectItem(":Note - .ComboBox.list_JList", "ORCL"), 79, 13, 0, Button.Button1)
    snooze(1)
    type(waitForObject(":Note - ORACLE CORP_JTextPane"), "TEST ORCL")
    snooze(1)
    clickButton(waitForObject(":Note - ORACLE CORP.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Export to CSV_FixedSizeButton"))
    snooze(2)
    clickButton(waitForObject(":Save.Cancel_JButton"))

    snooze(3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_MQMenuBar_2", "Tools"))
    activateItem(waitForObjectItem(":Tools_JMenu_3", "__Preferences..."))
    mouseClick(waitForObjectItem(":Preferences.com.futuresource.livecharts.common.LCCardList$1_LCList", "Appearance  "), 36, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Preferences.Group available windows in context menu_LCCheckBox"), 12, 9, 0, Button.Button1)
    clickButton(waitForObject(":Preferences.Apply_FixedSizeButton"))
    clickButton(waitForObject(":Preferences.OK_FixedSizeButton"))

    snooze(3)



    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 109, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_10", "News"))
    test.compare(waitForObjectExists(":News.News_LCLabel_2").name, "News")
    clickButton(waitForObject(":News_JButton"))

    snooze(2)

#     mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 17, 8, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_9", "Chart"))
#     snooze(1)
#     activateItem(waitForObjectItem(":Chart_JMenu_16", "Default"))
#     snooze(2)
#     clickButton(waitForObject(":Chart_JButton"))
#     snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 11, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Stock Options"))
    snooze(2)
    clickButton(waitForObject(":Stock Options_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 27, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Detailed Quotes"))
    snooze(2)
    clickButton(waitForObject(":Detailed Quotes_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 46, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Time & Sales"))
    snooze(2)
    clickButton(waitForObject(":Time & Sales_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 22, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Market Depth"))
    snooze(2)
    clickButton(waitForObject(":Market Depth_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 26, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Net House"))
    snooze(2)
    clickButton(waitForObject(":Net House_JButton"))
    snooze(2)
    
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 16, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Strip Calculator"))
    snooze(2)
    clickButton(waitForObject(":Strip Calculator_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 46, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "S&P Research Stock Quick View"))
    snooze(2)
    clickButton(waitForObject(":S&P Research Stock Quick View_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 27, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Spread Matrix"))
    snooze(2)
    clickButton(waitForObject(":Spread Matrix_JButton"))
    snooze(2)
    
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 15, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Fixed Pages"))
    snooze(2)
    clickButton(waitForObject(":Fixed Pages_JButton_2"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 20, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Trade Manager"))
    snooze(2)
    clickButton(waitForObject(":Trade Manager_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 36, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Grid"))
    snooze(2)
    clickButton(waitForObject(":Grid_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 18, 1, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Short Interest / Volume"))
    snooze(2)
    clickButton(waitForObject(":Short Interest / Volume_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 27, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "View"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.View_JMenu_8", "Broker Share"))
    snooze(2)
    clickButton(waitForObject(":Broker Share_JButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 8, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_5", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_10", "Global Indicies"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Watch List_MonsoonNewPadButton"))
    clickButton(waitForObject(":Watch List.Symbol List_LCTreeButton"))
    mouseClick(waitForObjectItem(":Watch List_LCTree", ".Workspace Symbol Lists.Global Indicies"), 77, 9, 0, Button.Button1)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.16_0_TableItemProxy").text, "IBM")
    clickButton(waitForObject(":Watch List_JButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "1/0"), 18, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Add To Symbol list_JMenu_5", "Mobile Home Page (Phone Only)"))
    activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_4", "US"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA.Watch List_MonsoonNewPadButton"))
    clickButton(waitForObject(":Watch List.Symbol List_LCTreeButton"))
    mouseClick(waitForObjectItem(":Watch List_LCTree", ".Mobile Home Page (Phone Only).US"), 32, 9, 0, Button.Button1)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.7_0_TableItemProxy").text, "ORCL")
    clickButton(waitForObject(":Watch List_JButton"))
    test.passes("Pass")
    snooze(2)

#     mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 20, 11, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Alerts"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_11", "Add Quote Alert"))
#     type(waitForObject(":Add Quote Alert_LCTextField_4"), "135")
#     mouseClick(waitForObject(":Add Quote Alert.Link To:_LCCheckBox"), 9, 6, 0, Button.Button1)
#     mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 125, 4, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Add Quote Alert.ComboBox.list_JList_2", "Page 2"), 96, 2, 0, Button.Button1)
#     mouseClick(waitForObject(":Add Quote Alert_LCTextArea"), 47, 19, 0, Button.Button1)
#     type(waitForObject(":Add Quote Alert_LCTextArea"), "test")
#     clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
#     snooze(3)
    
#     mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 13, 9, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Alerts"))
#     activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_11", "Add News Alert"))
#     mouseClick(waitForObject(":Add News Alert.Link To:_LCCheckBox"), 9, 10, 0, Button.Button1)
#     mouseClick(waitForObject(":Add News Alert.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 105, 14, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Add News Alert.ComboBox.list_JList", "Page 2"), 74, 11, 0, Button.Button1)
#     mouseClick(waitForObject(":Add News Alert_LCTextArea"), 74, 11, 0, Button.Button1)
#     type(waitForObject(":Add News Alert_LCTextArea"), "test")
#     clickButton(waitForObject(":Add News Alert.OK_FixedSizeButton"))
# 
#     snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 15, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Alerts"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Alerts_JMenu_6", "__Alerts"))
    test.compare(waitForObjectExists(":Alerts.Alerts_LCLabel_3").text, "Alerts")
    clickButton(waitForObject(":Alerts_JButton"))

    snooze(3)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 21, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Trade"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade_JMenu_5", "Buy IBM"))
    test.compare(waitForObjectExists(":Order Ticket - New Order.Buy_TradeButton").actioncommand, "Buy")
    clickButton(waitForObject(":Order Ticket - New Order.Cancel_FixedSizeButton"))
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 25, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Trade"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade_JMenu_5", "Sell IBM"))
    test.compare(waitForObjectExists(":Order Ticket - New Order.Sell_TradeButton").actioncommand, "Sell")
    clickButton(waitForObject(":Order Ticket - New Order.Cancel_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 14, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Trade Details"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade Details_JMenu_4", "Show Positions"))
    test.compare(waitForObjectExists(":Account Manager.Account Manager_LCLabel").text, "Account Manager")
    clickButton(waitForObject(":Account Manager_JButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 21, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Trade Details"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade Details_JMenu_4", "Show Orders"))
    test.compare(waitForObjectExists(":Account Manager.Account Manager_LCLabel").name, "Account Manager")
    clickButton(waitForObject(":Account Manager_JButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 38, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Trade Details"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Trade Details_JMenu_4", "Show Executions"))
    test.compare(waitForObjectExists(":Account Manager.Account Manager_LCLabel").name, "Account Manager")
    clickButton(waitForObject(":Account Manager_JButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 17, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Create Expression Shortcut for IBM"))
    type(waitForObject(":Add Expression Shortcut_LCUppercaseTextField"), "TEST NOTES")
    mouseClick(waitForObject(":Add Expression Shortcut_LCTextArea_2"), 20, 43, 0, Button.Button1)
    type(waitForObject(":Add Expression Shortcut_LCTextArea_2"), "TEST FOR SHPRTCUT")
    clickButton(waitForObject(":Add Expression Shortcut.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)

    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 17, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Sort"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Sort_JMenu", "Sort By Symbol Ascending"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 2, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Sort"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Sort_JMenu", "Sort By Symbol Descending"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 14, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Print"))
    clickButton(waitForObject(":Print Notes.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 11, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    mouseClick(waitForObject(":Notes Display Properties_CommonButton_2"), 2, 8, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Notes Display Properties.ComboBox.list_JList", "14"), 6, 6, 0, Button.Button1)
    mouseClick(waitForObject(":Notes Display Properties_CommonButton_2"), 7, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Notes Display Properties.ComboBox.list_JList", "18"), 17, 3, 0, Button.Button1)
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 22, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_8", "Save Notes Properties As Default"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 23, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_8", "Apply Default Properties to the Notes"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Notes"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 24, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_8", "Apply Default Properties to all Notes Windows"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Notes"))
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 11, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Defaults"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Defaults_JMenu_8", "Remove Default Notes Properties"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_4"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Notes"))
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 12, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_2").text, "Text & Colors")
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 7, 1, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    mouseClick(waitForObject(":Notes Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 99, 10, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Notes Display Properties.ComboBox.list_JList", "Open Sans Semibold"), 84, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Notes Display Properties_CommonButton_2"), 4, 1, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Notes Display Properties.ComboBox.list_JList", "14"), 17, 18, 0, Button.Button1)
    mouseClick(waitForObject(":Notes Display Properties.Bold_LCCheckBox"), 18, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Notes Display Properties.Italic_LCCheckBox"), 7, 10, 0, Button.Button1)
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 22, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_5"))
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 29, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 20, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_7"))
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "1/0"), 21, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Notes Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Gridlines  "), 46, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Notes Display Properties.Show Horizontal Gridlines_LCCheckBox"), 13, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Notes Display Properties.Show Vertical Gridlines_LCCheckBox"), 13, 11, 0, Button.Button1)
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "1/0"), 20, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.com.futuresource.livecharts.notes.NotesTable_NotesTable", "Display Properties..."))
    mouseClick(waitForObject(":Notes Display Properties.Show Horizontal Gridlines_LCCheckBox"), 11, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Notes Display Properties.Show Vertical Gridlines_LCCheckBox"), 10, 11, 0, Button.Button1)
    clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")

    snooze(30)
#     clickButton(waitForObject(":Connect_JButton_4"))
#     activateItem(waitForObjectItem(":Connect_JButton_4", "Notes"))
#     mouseClick(waitForObject(":Notes.Notes_LCLabel"), 39, 9, 0, Button.Button1)
#     waitFor("object.exists(':Notes.Notes_LCLabel')", 20000)
#     test.compare(findObject(":Notes.Notes_LCLabel").name, "Notes")
#     clickButton(waitForObject(":Notes.Add_FixedSizeButton"))
#     mouseClick(waitForObject(":Note - _LCTextField"), 13, 6, 0, Button.Button1)
#     type(waitForObject(":Note - _LCTextField"), "aapl")
#     mouseClick(waitForObject(":Note - _JTextPane"), 32, 18, 0, Button.Button1)
#     snooze(2)
#    # mouseClick(waitForObject(":_JTextPane"), 39, 24, 0, Button.Button1)
#     type(waitForObject(":Note - APPLE INC_JTextPane"), "test it.")
#     clickButton(waitForObject(":Note - APPLE INC. _FixedSizeButton"))
#     clickButton(waitForObject(":Note - APPLE INC_FixedSizeButton"))
#     mouseClick(waitForObject(":Note - APPLE INC_LCToggleButton"), 9, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Note - APPLE INC_LCToggleButton_2"), 11, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Note - APPLE INC_LCToggleButton_3"), 11, 8, 0, Button.Button1)
#     clickButton(waitForObject(":Note - APPLE INC.OK_FixedSizeButton"))
#     mouseClick(waitForObjectItem(":Notes.com.futuresource.livecharts.notes.NotesTable_NotesTable", "0/0"), 104, 6, 0, Button.Button1)
#     clickButton(waitForObject(":Notes.Edit_FixedSizeButton"))
#     type(waitForObject(":Note - APPLE INC_JTextPane"), "again")
#     clickButton(waitForObject(":Note - APPLE INC.OK_FixedSizeButton"))
#     clickButton(waitForObject(":Notes.Delete_FixedSizeButton"))
#     mouseClick(waitForObject(":Question_LCTitlePane"), 41, 11, 0, Button.Button1)
#     clickButton(waitForObject(":Question.No_FixedSizeButton"))
#     clickButton(waitForObject(":Notes.Delete All_FixedSizeButton"))
#     mouseClick(waitForObject(":Question_LCTitlePane"), 47, 21, 0, Button.Button1)
#     clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
#     clickButton(waitForObject(":Notes.Import from CSV_FixedSizeButton"))
#     clickButton(waitForObject(":Open.Cancel_JButton"))
#     clickButton(waitForObject(":Notes.Export to CSV_FixedSizeButton"))
#     clickButton(waitForObject(":Save.Close_JButton"))
#     mouseClick(waitForObject(":Notes_TableHeaderItemProxy"), 202, 7, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Notes_LCTableHeader", "Sort By Notes Ascending"))
#     mouseClick(waitForObject(":Notes_TableHeaderItemProxy"), 199, 16, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Notes_LCTableHeader", "Sort By Notes Descending"))
#     mouseClick(waitForObject(":Notes_JViewport"), 299, 64, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Notes.Notes_NotesPad", "Add Note"))
#     mouseClick(waitForObject(":Note - _LCTitlePane"), 71, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Note - .Cancel_FixedSizeButton"))
#     mouseClick(waitForObject(":Notes_JViewport"), 404, 84, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Notes.Notes_NotesPad", "Defaults"))
#     activateItem(waitForObjectItem(":Notes.Defaults_JMenu", "Save Notes Properties As Default"))
#     mouseClick(waitForObject(":Information_LCTitlePane"), 42, 15, 0, Button.Button1)
#     clickButton(waitForObject(":Information.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Notes_JPanel"), 160, 10, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Notes_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Notes Display Properties_LCTitlePane"), 96, 15, 0, Button.Button1)
#     mouseClick(waitForObject(":Notes Display Properties_CommonButton"), 7, 7, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Notes Display Properties.ComboBox.list_JList", "Open Sans Extrabold"), 77, 16, 0, Button.Button1)
#     mouseClick(waitForObject(":Notes Display Properties_CommonButton_2"), 9, 5, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Notes Display Properties.ComboBox.list_JList", "15"), 17, 5, 0, Button.Button1)
#     mouseClick(waitForObject(":Notes Display Properties.Bold_LCCheckBox"), 9, 8, 0, Button.Button1)
#     mouseClick(waitForObject(":Notes Display Properties.Italic_LCCheckBox"), 13, 6, 0, Button.Button1)
#     clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton"))
#     clickButton(waitForObject(":Notes Display Properties_FixedSizeButton"))
#     clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton_2"))
#     clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton_3"))
#     clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_3"))
#     mouseClick(waitForObjectItem(":Notes Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Gridlines  "), 55, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Notes Display Properties.Show Horizontal Gridlines_LCCheckBox"), 13, 17, 0, Button.Button1)
#     mouseClick(waitForObject(":Notes Display Properties.Show Vertical Gridlines_LCCheckBox"), 13, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Notes Display Properties. _FixedSizeButton_4"))
#     #clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_4"))
#     clickButton(waitForObject(":Notes Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Notes Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Notes_JPanel"), 327, 14, 0, Button.Button1)
#     clickButton(waitForObject(":Notes_JButton")) 
    
    Forex()
    
