def Weather():
    
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Weather"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Weather_LCLabel").text, "Weather")
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Select map..._LCTreeButton"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.Current US Temperatures"), 66, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy Current US Temperatures_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.US Current Surface Front"), 96, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy US Current Surface Front_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.US Forecast Surface Front"), 47, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy US Forecast Surface Front_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.6-10 Day Temperature Forecast"), 67, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy 6-10 Day Temperature Forecast_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.US Observed Low Temps__"), 70, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy US Observed Low Temps._LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.US Observed High Temps__"), 102, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy US Observed High Temps._LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.Today's US Max Temp__ Forecast"), 113, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy Today's US Max Temp. Forecast_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.Tomorrow's US Max Temp__ Forecast"), 104, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy Tomorrow's US Max Temp. Forecast_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.Day 3 US Max Temp__ Forecast"), 110, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy Day 3 US Max Temp. Forecast_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy.Day 4 US Max Temp__ Forecast"), 119, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Energy Day 4 US Max Temp. Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Energy"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture.Current Temperatures"), 53, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Agriculture Current Temperatures_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture.Current Surface Front"), 47, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Agriculture Current Surface Front_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture II"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture II.US Seasonal Drought Outlook"), 48, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Agriculture II US Seasonal Drought Outlook_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture II.Soil Moisture - Most Recent Day"), 155, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.US Agriculture II Soil Moisture - Most Recent Day_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".US Agriculture II"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Regional US Radar Maps"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Regional US Radar Maps.West Southwest US (CA)"), 34, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Regional US Radar Maps West Southwest US (CA)_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Regional US Radar Maps.Southeast US (GA)"), 70, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Regional US Radar Maps Southeast US (GA)_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Regional US Radar Maps"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Metro US Radar Maps"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Metro US Radar Maps.Chicago Illinois"), 48, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Metro US Radar Maps Chicago Illinois_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Metro US Radar Maps"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Canada Accumulated Precipitation"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Canada Accumulated Precipitation.Central Observed Precipitation"), 22, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Canada Accumulated Precipitation Central Observed Precipitation_LCTreeButton"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".South America"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".South America.Argentina Min Temp Day 3"), 66, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.South America Argentina Min Temp Day 3_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".South America"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Europe"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Europe.Today's Lows"), 14, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Europe Today's Lows_LCTreeButton"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Europe.HDD Day 3"), 33, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Europe HDD Day 3_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Europe"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Europe"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Europe.Day 2 Rainfall Forecast"), 80, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Southeastern Europe Day 2 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Europe"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northeastern Europe"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northeastern Europe.Day 1 Rainfall Forecast"), 46, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Northeastern Europe Day 1 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northeastern Europe"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Australia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Australia.Tomorrow Wind Forecast Australia"), 14, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Australia Tomorrow Wind Forecast Australia_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Australia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northeastern Australia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northeastern Australia.Day 5 Wind Forecast Northeastern Australia"), 36, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Northeastern Australia Day 5 Wind Forecast Northeastern Australia_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northeastern Australia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Australia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Australia.Day 4 Wind Forecast Southeastern Australia"), 51, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Southeastern Australia Day 4 Wind Forecast Southeastern Australia_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Australia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Western Australia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Western Australia.Tomorrow Wind Forecast Western Australia"), 69, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Western Australia Tomorrow Wind Forecast Western Australia_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Western Australia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Africa"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Africa.Day 6 Rainfall Forecast"), 74, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Africa Day 6 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Africa"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Western Africa"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Western Africa.Day 2 Rainfall Forecast"), 32, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Western Africa Day 2 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Western Africa"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northwestern Africa"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northwestern Africa.Day 5 Rainfall Forecast"), 48, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Northwestern Africa Day 5 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Northwestern Africa"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Eastern Africa"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Eastern Africa.Day 3 Max Temp__ Forecast"), 79, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Eastern Africa Day 3 Max Temp. Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Eastern Africa"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Mideastern Africa"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Mideastern Africa.Tomorrow's Max Temp__ Forecast"), 64, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Mideastern Africa Tomorrow's Max Temp. Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Mideastern Africa"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".South Africa"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".South Africa.Day 3 Max Temp__ Forecast"), 22, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.South Africa Day 3 Max Temp. Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".South Africa"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Russia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Russia.Day 4 Rainfall Forecast"), 63, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Russia Day 4 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Russia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Asia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Asia.Tomorrow's Max Temp__ Forecast"), 84, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Asia Tomorrow's Max Temp. Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Asia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Asia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Asia.Day 3 Max Temp__ Forecast"), 32, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Southeastern Asia Day 3 Max Temp. Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Southeastern Asia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".China/Japan"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".China/Japan.Day 7 Rainfall Forecast"), 110, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.China/Japan Day 7 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".China/Japan"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".India"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".India.Day 4 Max Temp__ Forecast"), 97, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.India Day 4 Max Temp. Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".India"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Indonesia"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Indonesia.Day 3 Rainfall Forecast"), 60, 9, 0, Button.Button1)
    snooze(3)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA.Indonesia Day 3 Rainfall Forecast_LCTreeButton"))
    collapse(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".Indonesia"))
    expand(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".India"))
    mouseClick(waitForObjectItem(":Data & Analytics NYSE QA_LCTree", ".India.Day 7 Rainfall Forecast"), 73, 9, 0, Button.Button1)
    snooze(2)

    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 22, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Watch List"))
    activateItem(waitForObjectItem(":Watch List_JMenu_11", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 34, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Quotes Grid"))
    activateItem(waitForObjectItem(":Quotes Grid_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 34, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Chart"))
    activateItem(waitForObjectItem(":Chart_JMenu_22", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 24, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Stock Options"))
    activateItem(waitForObjectItem(":Stock Options_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 17, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "News"))
    activateItem(waitForObjectItem(":News_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 17, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Hot Lists"))
    activateItem(waitForObjectItem(":Hot Lists_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 38, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Detailed Quotes"))
    activateItem(waitForObjectItem(":Detailed Quotes_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 31, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Alerts"))
    activateItem(waitForObjectItem(":Alerts_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 22, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Time & Sales"))
    activateItem(waitForObjectItem(":Time & Sales_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 10, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Market Depth"))
    activateItem(waitForObjectItem(":Market Depth_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 13, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Net House"))
    activateItem(waitForObjectItem(":Net House_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 20, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Web Feeds"))
    activateItem(waitForObjectItem(":Web Feeds_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 31, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Weather"))
    activateItem(waitForObjectItem(":Weather_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 13, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Fundamentals"))
    activateItem(waitForObjectItem(":Fundamentals_JMenu_10", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 43, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Research Center"))
    activateItem(waitForObjectItem(":Research Center_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 18, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Browser"))
    activateItem(waitForObjectItem(":Browser_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 21, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "ETFs & Funds"))
    activateItem(waitForObjectItem(":ETFs & Funds_JMenu_8", "US ETF Profile"))
    activateItem(waitForObjectItem(":US ETF Profile_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 25, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Market Rates"))
    activateItem(waitForObjectItem(":Market Rates_JMenu_7", "US Markets Rates"))
    activateItem(waitForObjectItem(":US Markets Rates_JMenu_7", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 34, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Market Rates"))
    activateItem(waitForObjectItem(":Market Rates_JMenu_7", "N. Amer Markets Rates"))
    activateItem(waitForObjectItem(":N. Amer Markets Rates_JMenu_5", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 20, 1, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Forex"))
    activateItem(waitForObjectItem(":Forex_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 15, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Future Options"))
    activateItem(waitForObjectItem(":Future Options_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 13, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Future Options"))
    activateItem(waitForObjectItem(":Future Options_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 20, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "Strip Calculator"))
    activateItem(waitForObjectItem(":Strip Calculator_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 34, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "S&P Research"))
    activateItem(waitForObjectItem(":S&P Research_JMenu_8", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 12, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "S&P Research Stock Quick View"))
    activateItem(waitForObjectItem(":S&P Research Stock Quick View_JMenu_7", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 26, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "New"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.New_JMenu_15", "S&P Research Mutual Fund Quick View"))
    activateItem(waitForObjectItem(":S&P Research Mutual Fund Quick View_JMenu_7", "To the right"))
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 27, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA. _LCLabel_10"), 4, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Window Title"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Weather_LCLabel").name, "Weather")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 20, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Show Titlebar description"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.Weather_LCLabel_2").text, "Weather")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel_2"), 20, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Customize Titlebar Description..."))
    type(waitForObject(":Titlebar Description Settings.Weather_LCTextArea"), "test ")
    mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 11, 7, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_6"))
    mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 11, 13, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_8"))
    setValue(waitForObject(":Titlebar Description Settings., Transparency: _LCSpinner"), 49)
    setValue(waitForObject(":Titlebar Description Settings., Transparency: _LCSpinner"), 48)
    mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 8, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 82, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "PMingLiU"), 67, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 12, 8, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "14"), 10, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 14, 4, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 4, 4, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 16, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Out"))
    test.compare(waitForObjectExists(":Weather.test Weather_LCLabel").text, "test Weather")
    snooze(2)
    
    mouseClick(waitForObject(":Weather.test Weather_LCLabel"), 33, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Weather_TitlebarPanel", "Attach"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 28, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Cut Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Empty Window_LCLabel"), 30, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Weather"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Weather_JMenu", "In this window"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.test Weather_LCLabel").text, "test Weather")
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 27, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 33, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Weather"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Weather_JMenu", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.test Weather_LCLabel_2").text, "test Weather")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 41, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Copy Window Image"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 15, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Paste Weather"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA.Paste Weather_JMenu", "To the right"))
    test.compare(waitForObjectExists(":Data & Analytics NYSE QA.test Weather_LCLabel_2").text, "test Weather")
    snooze(2)
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton"))
    snooze(1)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 26, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Send Image by E-mail..."))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 24, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Take Custom Screenshot"))
    mouseDrag(waitForObject(":Data & Analytics NYSE QA.com.futuresource.livecharts.common.LCLabel_LCLabel"), 10, 2, 1306, 495, Modifier.None, Button.Button1)
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 10, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Print"))
    clickButton(waitForObject(":Print Weather.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 16, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    mouseClick(waitForObject(":Weather Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 92, 10, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Weather Display Properties.ComboBox.list_JList", "Open Sans Extrabold"), 69, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Weather Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 17, 13, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Weather Display Properties.ComboBox.list_JList", "16"), 15, 1, 0, Button.Button1)
    mouseClick(waitForObject(":Weather Display Properties.com.futuresource.livecharts.common.LCPanel_LCPanel"), 172, 52, 0, Button.Button1)
    clickButton(waitForObject(":Weather Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Weather Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Weather Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Weather Display Properties_FixedSizeButton_5"))
    clickButton(waitForObject(":Weather Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Weather Display Properties_FixedSizeButton_5"))
    clickButton(waitForObject(":Weather Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Weather Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Weather Display Properties.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA_JPanel_18"), 231, 153, 0, Button.Button1)
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 12, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    mouseClick(waitForObject(":Weather Display Properties.Keep aspect ratio_LCCheckBox"), 9, 3, 0, Button.Button1)
    mouseClick(waitForObject(":Weather Display Properties.Show Key_LCCheckBox"), 9, 9, 0, Button.Button1)
    clickButton(waitForObject(":Weather Display Properties.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 21, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Display Properties"))
    mouseClick(waitForObject(":Weather Display Properties.Show Key_LCCheckBox"), 15, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Weather Display Properties.Keep aspect ratio_LCCheckBox"), 14, 7, 0, Button.Button1)
    clickButton(waitForObject(":Weather Display Properties.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObject(":Data & Analytics NYSE QA.test Weather_LCLabel"), 12, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Empty"))
    snooze(2)
    
    clickButton(waitForObject(":Data & Analytics NYSE QA_JButton_7"))
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_JButton_7", "Weather"))
    mouseClick(waitForObject(":Data & Analytics NYSE QA.Weather_LCLabel"), 24, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Data & Analytics NYSE QA_TitlebarPanel", "Close"))

    snooze(30)

#     clickButton(waitForObject(":Connect_JButton_4"))
#     activateItem(waitForObjectItem(":Connect_JButton_4", "Weather"))
#     mouseClick(waitForObject(":Weather.Weather_LCLabel"), 26, 9, 0, Button.Button1)
#     waitFor("object.exists(':Weather.Weather_LCLabel')", 20000)
#     test.compare(findObject(":Weather.Weather_LCLabel").name, "Weather")
#     clickButton(waitForObject(":Weather.Select map..._LCTreeButton"))
#     expand(waitForObjectItem(":Weather_LCTree", ".US Energy"))
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".US Energy.US Forecast Surface Front"), 55, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather.US Energy US Forecast Surface Front_LCTreeButton"))
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".US Energy.Today's US Min Temp__ Forecast"), 87, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather.US Energy Today's US Min Temp. Forecast_LCTreeButton"))
#     setValue(waitForObject(":Weather_JScrollBar"), 360)
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".US Energy.US CDD Deviation Day 3"), 122, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather.US Energy US CDD Deviation Day 3_LCTreeButton"))
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".US Energy.US CDD Deviation Day 6"), 123, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather.US Energy US CDD Deviation Day 6_LCTreeButton"))
#     setValue(waitForObject(":Weather_JScrollBar"), 720)
#     setValue(waitForObject(":Weather_JScrollBar"), 1080)
#     expand(waitForObjectItem(":Weather_LCTree", ".Europe"))
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".Europe.CDD Day 3"), 26, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather.Europe CDD Day 3_LCTreeButton"))
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".Europe.CDD Day 6"), 21, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather.Europe CDD Day 6_LCTreeButton"))
#     setValue(waitForObject(":Weather_JScrollBar"), 1674)
#     setValue(waitForObject(":Weather_JScrollBar"), 2034)
#     expand(waitForObjectItem(":Weather_LCTree", ".Australia"))
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".Australia.Day 3 AM Precip Australia"), 52, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather.Australia Day 3 AM Precip Australia_LCTreeButton"))
#     setValue(waitForObject(":Weather_JScrollBar"), 2664)
#     setValue(waitForObject(":Weather_JScrollBar"), 2664)
#     mouseClick(waitForObjectItem(":Weather_LCTree", ".Australia.Day 5 Min Temp Forecast Australia"), 98, 9, 0, Button.Button1)
#     mouseClick(waitForObject(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel"), 565, 144, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel", "Show Tree"))
#     mouseClick(waitForObjectItem(":Weather_JWeatherTree", "All Maps.Northeastern Australia"), 67, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Weather_JWeatherTree", "All Maps.Southeastern Australia"), 61, 9, 0, Button.Button1)
#     dragItemBy(waitForObject(":Weather_LCRootPane"), 0, 352, -86, -5, Modifier.None, Button.Button1)
#     mouseDrag(waitForObject(":Weather_BasicSplitPaneDivider"), 5, 219, 55, 0, Modifier.None, Button.Button1)
#     setValue(waitForObject(":Weather_JScrollBar_2"), 0)
#     expand(waitForObjectItem(":Weather_JWeatherTree", "All Maps.Southeastern Australia"))
#     mouseClick(waitForObjectItem(":Weather_JWeatherTree", "All Maps.Southeastern Australia.Tomorrow PM Preceip Southeastern Australia"), 42, 9, 0, Button.Button1)
#     mouseClick(waitForObject(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel"), 300, 152, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel", "Keep aspect ratio"))
#     mouseClick(waitForObject(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel"), 351, 213, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel", "Defaults"))
#     activateItem(waitForObjectItem(":Weather.Defaults_JMenu", "Save Weather Properties As Default"))
#     mouseClick(waitForObject(":Information_LCTitlePane"), 41, 13, 0, Button.Button1)
#     clickButton(waitForObject(":Information.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel"), 345, 118, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Weather.com.futuresource.livecharts.jweather.MapPanel_MapPanel", "Display Properties..."))
#     mouseClick(waitForObject(":Weather Display Properties_CommonButton"), 7, 9, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Weather Display Properties.ComboBox.list_JList", "PMingLiU"), 67, 1, 0, Button.Button1)
#     mouseClick(waitForObject(":Weather Display Properties_CommonButton_2"), 8, 6, 0, Button.Button1)
#     mouseClick(waitForObjectItem(":Weather Display Properties.ComboBox.list_JList", "15"), 9, 9, 0, Button.Button1)
#     mouseClick(waitForObject(":Weather Display Properties.Show Key_LCCheckBox"), 10, 8, 0, Button.Button1)
#     mouseClick(waitForObject(":Weather Display Properties.Keep aspect ratio_LCCheckBox"), 14, 9, 0, Button.Button1)
#     clickButton(waitForObject(":Weather Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Weather_JPanel"), 408, 13, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Weather_TitlebarPanel", "Display Properties"))
#     mouseClick(waitForObject(":Weather Display Properties.Show Key_LCCheckBox"), 17, 12, 0, Button.Button1)
#     mouseClick(waitForObject(":Weather Display Properties.Keep aspect ratio_LCCheckBox"), 5, 11, 0, Button.Button1)
#     clickButton(waitForObject(":Weather Display Properties. _FixedSizeButton"))
#     clickButton(waitForObject(":Weather Display Properties_FixedSizeButton"))
#     clickButton(waitForObject(":Weather Display Properties. _FixedSizeButton_2"))
#     clickButton(waitForObject(":Weather Display Properties_FixedSizeButton_2"))
#     clickButton(waitForObject(":Weather Display Properties. _FixedSizeButton_3"))
#     clickButton(waitForObject(":Weather Display Properties_FixedSizeButton_3"))
#     clickButton(waitForObject(":Weather Display Properties.OK_FixedSizeButton"))
#     mouseClick(waitForObject(":Weather_JPanel_2"), 702, 15, 0, Button.Button1)
#     clickButton(waitForObject(":Weather_JButton"))


    
    Notes()
